### ISSUE TITLE
Image not showing in thumbnail

### ISSUE THREAD

**Issue by lyturn** [dyphire/mpv-config#1]
![013](https://user-images.githubusercontent.com/91406367/160862357-c6848420-b574-4cff-8794-0cb52cec4ecf.png)

**Comment by dyphire** [comment]
You may lack the environment variable of ffmpeg. Please set it and try again.

You can also choose to specify the path of ffmpeg in the thumbnailer.conf through the option of exec_path.

**Comment by lyturn** [comment]
Both the ffmpeg environment variable and the exec_path path are set, but it still doesn't work.

**Comment by dyphire** [comment]
Can not reproduce.

**Comment by lyturn** [comment]
Cached files are all 0 bytes
![014](https://user-images.githubusercontent.com/91406367/161048940-c667e9b1-332e-4fe2-a202-8d1a8181a1cb.png)

**Comment by dyphire** [comment]
> Cached files are all 0 bytes 

Are you using my script of thumbnailer.lua? This problem looks like an upstream bug: https://github.com/deus0ww/mpv-conf/commit/cc10823a0a9340fb58717e66cbbe37f2e05b27aa. I have revert the relevant code before: https://github.com/dyphire/mpv-config/commit/02b1a23f32fa94f1c119e9d7c299ce8615c3f896.

So you should report it to the [correct tracker](https://github.com/deus0ww/mpv-conf/issues) , not here.

**Comment by lyturn** [comment]
I'm using your script and that's why I'm asking here.

**Comment by dyphire** [comment]
> I'm using your script and that's why I'm asking here.

I can only reproduce this problem through the upstream script.

Can you download my script again, delete the cache and test?
