### ISSUE TITLE
Can we add frame padding function in the later stage of mpv config?

### ISSUE THREAD

**Issue by laodaoxp** [dyphire/mpv-config#100]
Hello, thank you very much for making the mpv config
Comprehensive settings and functions. The filters have also been integrated a lot.
I have been using it all along, and I sincerely appreciate it.
May I ask the author again:
Can we add frame filling function. Does it mean adding frame insertion function?
30fps=>60fps
60fps=>120fps
Or do you have this plan in the later stage?
Thanks again.

**Comment by dyphire** [comment]
no plan
