### ISSUE TITLE
有没有只做简单播放器的配置

### ISSUE THREAD

**Issue by Yumega** [dyphire/mpv-config#101]
只做播放器，只保留基本UI（关闭、最小化、全屏等），删除其他所有功能。
测试播放m3u8流几分钟后，内存占用量1.2G，iptvnator只占用600m

**Comment by dyphire** [comment]
m3u8 链接或文件给下，看下能不能复现

**Comment by dyphire** [comment]
可以继续观察下，看会不会再现。如何再现建议提供复现的步骤以便测试
