### ISSUE TITLE
dynamic-crop导致列表播放时，下一文件窗口初始位置不正常

### ISSUE THREAD

**Issue by nanachisol** [dyphire/mpv-config#102]
**mpv Information**
```
mpv v0.38.0-581-gacbd537d Copyright © 2000-2024 mpv/MPlayer/mplayer2 projects
 built on Jul  7 2024 01:05:03
libplacebo version: v7.349.0 (v7.349.0-dirty)
FFmpeg version: N-116197-g061913863
FFmpeg library versions:
   libavcodec      61.9.100
   libavdevice     61.2.100
   libavfilter     10.2.102
   libavformat     61.5.100
   libavutil       59.28.100
   libswresample   5.2.100
   libswscale      8.2.100
```
**Other Information**
- Windows version:Windows 11 Version 10.0.22631.3737
- GPU model, driver and version:ryzen 2700u with Vega10,AMD 24.5.1
- Source of mpv:zhongfly
- Introduced in version:N/A

**Reproduction Steps**
见附件

**Expected Behavior**
列表播放，下一视频文件窗口初始尺寸正常

**Actual Behavior**
列表播放，下一视频文件窗口初始尺寸异常

**Log File**
无

**Sample Files**
https://drive.google.com/file/d/13d4nJzwy35gU6pmZT3OzuKbWMayI4ruT/view?usp=sharing

**Comment by dyphire** [comment]
这是一个脚本错误，已经在最新提交中修复并调整了选项说明
顺便发现了另一个问题：mpv 在最大化窗口下切换列表文件时默认行为会退出最大化调整为视频大小，我认为这一行为不正确，同样在最新提交中修改为保持最大化窗口：https://github.com/dyphire/mpv-config/commit/857e868
