### ISSUE TITLE
预设配置组nnedi3，导致aspect ratio不正确

### ISSUE THREAD

**Issue by nanachisol** [dyphire/mpv-config#109]
如题，下附样本
[sample files](https://github.com/user-attachments/files/16563255/02.2015.01.26.-00.10.41.608-00.11.54.835.zip)

**Comment by dyphire** [comment]
跟 nnedi3 无关，即使你清除着色器配置也是一样
样本本身的元数据就有问题，使用其他播放也不会发生变化：
![image](https://github.com/user-attachments/assets/31c11e19-cfac-4647-b2d9-4d2b7d4ed51e)

**Comment by dyphire** [comment]
无法复现，只能自行排查你的配置了
![image](https://github.com/user-attachments/assets/775bbfb1-8287-48eb-b29f-c675ec8e7f21)
![image](https://github.com/user-attachments/assets/a8395889-eabb-431c-af1e-9104c30e56ac)

**Comment by dyphire** [comment]
现在看来很可能是跟 SSimSuperRes 着色器有关，另见 #187
