### ISSUE TITLE
file_brower访问SMB相关问题

### ISSUE THREAD

**Issue by redomCL** [dyphire/mpv-config#113]
大佬我又来挑错误了，先上日志：
![QQ截图20240820002637](https://github.com/user-attachments/assets/cccdaf8b-7995-4758-a79d-471c202939ad)

复现：U盘固态用USB插在PC1上，SMB共享，PC2将其挂载到本地作为网络驱动器后，file_brower访问该网络驱动器可以复现（访问闪退）。
![222](https://github.com/user-attachments/assets/5fd2da37-8663-4da2-91c7-32544a4b4767)

PC1：Windows10 LTSC 2019 8月累计更新
PC2：Windows10 专业工作站版 8月累积更新

**Comment by dyphire** [comment]
在 [CogentRedTester/mpv-file-browser](https://github.com/CogentRedTester/mpv-file-browser/issues) 上打开一个 issue，在这里报告我只会把这个无用的插件删了

**Comment by redomCL** [comment]
> > ~在 [CogentRedTester/mpv-file-browser](https://github.com/CogentRedTester/mpv-file-browser/issues) 上打开一个 issue，在这里报告我只会把这个无用的插件删了~
> > 仔细看了下，发现不知道什么时候这个脚本内容错掉了，已修正
> 
> 可是自从[97303d6](https://github.com/dyphire/mpv-config/commit/97303d6d18f4647808be3ce9648297dafc1b07cc) 之后，file-browser 的osd功能失效了 ![image](https://private-user-images.githubusercontent.com/155338130/361199990-28a62398-9756-48d6-a226-eeb9e20d8e6c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQ1ODc0NzMsIm5iZiI6MTcyNDU4NzE3MywicGF0aCI6Ii8xNTUzMzgxMzAvMzYxMTk5OTkwLTI4YTYyMzk4LTk3NTYtNDhkNi1hMjI2LWVlYjllMjBkOGU2Yy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODI1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgyNVQxMTU5MzNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1kZTM5MTg4YzIwMGQ1NDY3YWI2NWY0ZmE0MDVkMGZmMTNiYjJmMjkxNjk0MmM5NWRjNWMyYzVkMGI2NzdlMWJkJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.M5i50yTJzgJ6v8KRgw0Tf26mAPwRInZaCk7Mvnx571s)

确实有这个问题，应该是read_file.lua的问题，后面我通过测试，那些插件都删除了也不影响文件浏览器的基础功能，所以我就全删了。这个问题你好像得去上游原项目里反应，我测试上游也是这个问题。

**Comment by dyphire** [comment]
问题出在 wget 不像 curl 一样默认装在 win10/11 系统上，需要像 ffmpeg/ytdlp 一样自行安装。严格来说这不是脚本错误，是依赖错误。但使用 read-file.lua 的插件没有什么大用，在最新提交中精简，上次就该直接移除的。

> 那些插件都删除了也不影响文件浏览器的基础功能，所以我就全删了

不要乱删插件，home-label.lua、winroot.lua 和 winsort.lua 这几个插件对 windows 上的使用很重要

**Comment by redomCL** [comment]
> 问题出在 wget 不像 curl 一样默认装在 win10/11 系统上，需要像 ffmpeg/ytdlp 一样自行安装。严格来说这不是脚本错误，是依赖错误。但使用 read-file.lua 的插件没有什么大用，在最新提交中精简，上次就该直接移除的。
> 
> > 那些插件都删除了也不影响文件浏览器的基础功能，所以我就全删了
> 
> 不要乱删插件，winroot.lua 和 winsort.lua 这两个插件对 windows 上的使用提升很多

啊忘说了，我只保留了winroot.lua 和 winsort.lua
