### ISSUE TITLE
命令行调用问题

### ISSUE THREAD

**Issue by lsq** [dyphire/mpv-config#115]
![image](https://github.com/user-attachments/assets/c6f47f98-3df3-4063-ab57-ce8ade25aec6)
#### 第一个问题：
 这里提示`Get-Hash`不能识别；
#### 第二个问题：
![image](https://github.com/user-attachments/assets/68f5d8cc-d6e0-49b6-a092-5065d4778c82)
当系统路径中的lua5.4优先使用，会出现调用错误；如果把系统中scoop安装的lua5.4 uninstall，问题不复现，这个要怎么设置mpv调用自己目录下的lua

**Comment by Gerome100** [comment]
![image](https://github.com/user-attachments/assets/d1e75bae-5cd4-4c71-99b4-20d412838343)
I have a similar problem but I have to say that I use the English branch

**Comment by zhongfly** [comment]
> I have a similar problem but I have to say that I use the English branch

Because that script need `luasocket`, but shinchiro's build don't have it.Download mpv from https://github.com/dyphire/mpv-winbuild/releases

**Comment by verygoodlee** [comment]
识别不了 `Get-FileHash` 可能是powershell版本低于5，但是也不应该啊，powershell4是win8.1时代的东西了，win10内置的就是5了，执行下`powershell $PSVersionTable.PSVersion`检查版本

**Comment by dyphire** [comment]
> 第一个问题：
> 
> 这里提示Get-Hash不能识别；

> 识别不了 `Get-FileHash` 可能是powershell版本低于5，但是也不应该啊，powershell4是win8.1时代的东西了，win10内置的就是5了，执行下`powershell $PSVersionTable.PSVersion`检查版本

问题出在这里：
https://github.com/dyphire/mpv-config/blob/48bce8e407e368a6e4a4e2592fcc3b1834b5b98b/scripts/history-bookmark.lua#L152

history-bookmark.lua 代码中使用了 utils.join_path 来获取绝对路径，而 utils.join_path 无法正确处理和组合类似`./`和`../`这样的相对路径，它能接受的相对路径形式是`mpv test.mkv`和`mpv subdir\test.mkv`。
仅针对`.\`的简单修复方式，`..\`不可能得到修复，应该也没人在播放器中这么用：
```lua
path = utils.join_path(mp.get_property('working-directory'), path:gusb('^%.[\\/]',''))
```

> 当系统路径中的lua5.4优先使用，会出现调用错误；如果把系统中scoop安装的lua5.4 uninstall，问题不复现，这个要怎么设置mpv调用自己目录下的lua

依赖问题自行解决，这是 mpv 的问题，和此配置无关

**Comment by verygoodlee** [comment]
[normalize-path](https://mpv.io/manual/master/#command-interface-normalize-path)可以解决，但这个命令是近几个月才引入的，旧版本用不了
```lua
local utils = require('mp.utils')
print(mp.command_native({'normalize-path', utils.join_path('D:\\dir', '..\\a.mp4')}))
print(mp.command_native({'normalize-path', utils.join_path('D:\\', '.\\a.mp4')}))
```
输出
![image](https://github.com/user-attachments/assets/8c9ce128-0e60-4dfe-a153-24a8017b8c4d)

甚至可以不用手动拼working-directory `mp.command_native({'normalize-path', '.\\a.mp4'})` 会自动把工作目录拼上

**Comment by dyphire** [comment]
在提交 d3e1942 中为较新的 mpv 使用 normalize-path 命令处理路径

**Comment by Tony15246** [comment]
@dyphire 大佬，我今天在处理[这个issue](https://github.com/Tony15246/uosc_danmaku/issues/15#issuecomment-2410273453)的时候，发现normalize函数里这一行好像写错了方法名，不小心把gsub写成了gusb

```
path = utils.join_path(mp.get_property('working-directory'), path:gusb('^%.[\\/]',''))
```

我粗略搜索了一下，mpv-config项目在以下地方好像都有此问题

[[scripts/history-bookmark.lua](https://github.com/dyphire/mpv-config/blob/0bc026b098cf3e501fda1505bfc52bc1e404a9d3/scripts/history-bookmark.lua#L154)](https://github.com/dyphire/mpv-config/blob/0bc026b098cf3e501fda1505bfc52bc1e404a9d3/scripts/history-bookmark.lua#L154)

[[scripts/recentmenu.lua](https://github.com/dyphire/mpv-config/blob/0bc026b098cf3e501fda1505bfc52bc1e404a9d3/scripts/recentmenu.lua#L181)](https://github.com/dyphire/mpv-config/blob/0bc026b098cf3e501fda1505bfc52bc1e404a9d3/scripts/recentmenu.lua#L181)

[[scripts/simplehistory.lua](https://github.com/dyphire/mpv-config/blob/0bc026b098cf3e501fda1505bfc52bc1e404a9d3/scripts/simplehistory.lua#L407)](https://github.com/dyphire/mpv-config/blob/0bc026b098cf3e501fda1505bfc52bc1e404a9d3/scripts/simplehistory.lua#L407)

[[scripts/simplebookmark.lua](https://github.com/dyphire/mpv-config/blob/0bc026b098cf3e501fda1505bfc52bc1e404a9d3/scripts/simplebookmark.lua#L437)](https://github.com/dyphire/mpv-config/blob/0bc026b098cf3e501fda1505bfc52bc1e404a9d3/scripts/simplebookmark.lua#L437)

[[scripts/smartcopypaste_II.lua](https://github.com/dyphire/mpv-config/blob/0bc026b098cf3e501fda1505bfc52bc1e404a9d3/scripts/smartcopypaste_II.lua#L436)](https://github.com/dyphire/mpv-config/blob/0bc026b098cf3e501fda1505bfc52bc1e404a9d3/scripts/smartcopypaste_II.lua#L436)

[[scripts/playlistmanager.lua](https://github.com/dyphire/mpv-config/blob/0bc026b098cf3e501fda1505bfc52bc1e404a9d3/scripts/playlistmanager.lua#L350)](https://github.com/dyphire/mpv-config/blob/0bc026b098cf3e501fda1505bfc52bc1e404a9d3/scripts/playlistmanager.lua#L350)

**Comment by dyphire** [comment]
> @dyphire 大佬，我今天在处理[这个issue](https://github.com/Tony15246/uosc_danmaku/issues/15#issuecomment-2410273453)的时候，发现normalize函数里这一行好像写错了方法名，不小心把gsub写成了gusb
> 
> ```
> path = utils.join_path(mp.get_property('working-directory'), path:gusb('^%.[\\/]',''))
> ```
> 
> 我粗略搜索了一下，mpv-config项目在以下地方好像都有此问题

看到你那个提交后我才发现，本地修了还没推。是之前的提交 edcc335 引入的错误
