### ISSUE TITLE
请问为何播放下一个视频会卡死

### ISSUE THREAD

**Issue by kudoukouki** [dyphire/mpv-config#116]
[mpv.log](https://github.com/user-attachments/files/16965555/mpv.log)
很抱歉，bu'tai'hui'shi'yong'zhe'ge不太会使用这个软件，我想请教一下，为什么我点击下一个视频，就会卡死，视频是4k的
win11 7500f 6750GRE 32g内存

**Comment by dyphire** [comment]
日志中似乎没有什么有用的信息，但我可以本地反复播放退出和反复点击下一个按钮来复现它。目前可以确认删除 watch_later 下的缓存文件后播放功能正常，具体原因未知，可能是个 mpv 错误

**Comment by kudoukouki** [comment]
我播放其他视频，是正常的，那应该是视频问题吧
