### ISSUE TITLE
mpv_config-2024.09.14  input.conf 设置异常

### ISSUE THREAD

**Issue by laodaoxp** [dyphire/mpv-config#119]
Firstly, I would like to express my sincere gratitude to the author for their selfless dedication in continuously updating this script
I have been using it very well

mpv_config-2024.09.14：
input.conf 我修改后
F7                script-message-to uosc playlist                                                                         #menu: 打开 > 播放菜单
F8               script-message-to uosc chapters                                                                       #menu: 打开 > 章节菜单
F9                script-message-to uosc editions                                                                       #menu: 打开 > 版本菜单
F10                script-message-to uosc audio                                                                          #menu: 打开 > 其他音轨
F11               script-message-to uosc subtitles                                                                      #menu: 打开 > 其他字幕

#F5               script-message-to playlistmanager showplaylist;show-text ''                            #menu: 导航 > OSD 交互菜单 > 播放列表
#F6               script-message-to adevice_list toggle-adevice-browser;show-text ''                 #menu: 导航 > OSD 交互菜单 > 音频设备列表
#F7               script-message-to edition_list toggle-edition-browser;show-text ''                   #menu: 导航 > OSD 交互菜单 > 版本列表
#F8               script-message-to chapter_list toggle-chapter-browser;show-text ''                 #menu: 导航 > OSD 交互菜单 > 章节列表
#F9               script-message-to track_list toggle-vidtrack-browser;show-text ''                     #menu: 导航 > OSD 交互菜单 > 视频轨列表
#F10              script-message-to track_list toggle-audtrack-browser;show-text ''                  #menu: 导航 > OSD 交互菜单 > 音频轨列表
#F11              script-message-to track_list toggle-subtrack-browser;show-text ''                   #menu: 导航 > OSD 交互菜单 > 字幕轨列表

At this moment, when I am playing the video【这个时候我播放视频的时候】
I can press F7 to bring up the play menu. Press F7 once to close the play menu【我按一下F7 可以调出播放菜单。在按一下F7可以关闭播放菜单】
[mpv_config-2024.08.18] (https://github.com/dyphire/mpv-config/releases/tag/mpv_config-2024.08.18)
【Previous versions could be set in this way】以前的版本都可以这样设置

However, since upgrading mpv-config-2024.09.14, this operation is no longer possible
【但是自从升级mpv_config-2024.09.14以后这样操作就不可以了】 [mpv_config-2024.09.14](https://github.com/dyphire/mpv-config/releases/tag/mpv_config-2024.09.14) 
请问可以恢复到以前那样设置吗？拜托了
F7 F8 F9 F10 F11 Click once to open the interface. One click can close the interface

mpv_config-2024.08.18 以前的版本：
按一下F7 调出播放菜单界面
![1](https://github.com/user-attachments/assets/710585ca-6000-427b-a70a-86c0bdf3c4d0)

在一次按一下F7 ，取消播放菜单界面
![2](https://github.com/user-attachments/assets/e994b0e3-9b1a-4c0f-8614-042f35e408fb)

mpv_config-2024.09.14：新版本更新后，按第二次下F7 无法 取消播放菜单界面
![3](https://github.com/user-attachments/assets/a854fbcb-f77f-45f0-9cc2-e8b985577d05)

**Comment by laodaoxp** [comment]
原因我找到了 应该是 portable_config\scripts\uosc\elements\Menu.lua
这个文件里面 有修改.
请问作者.
可以F7 F8 F9 F10 F11 单击一次打开界面。在点击一次  关闭界面吗？

**Comment by dyphire** [comment]
这是因为 uosc 上游提交的特性变化导致的：https://github.com/tomasklaen/uosc/commit/07a1563，当 uosc 菜单时它强制接管 F1-12 的键位

改用其他键位绑定菜单即可正常通过同键位开关 uosc 菜单。这是 uosc 上游特性变化而非 bug，不会修复

**Comment by laodaoxp** [comment]
thankyou a lot
我把mpv_config-2024.08.18 里面的portable_config\scripts\uosc这个文件局覆盖到新版本里面用了 我还是喜欢用  F1-12 的键位.

**Comment by laodaoxp** [comment]
> 这是因为 uosc 上游提交的特性变化导致的：[tomasklaen/uosc@07a1563](https://github.com/tomasklaen/uosc/commit/07a1563) ，当 uosc 菜单打开时它会强制接管 F1-12 的键位
> 
> 改用其他键位绑定菜单即可正常通过同键位开关 uosc 菜单。这是 uosc 上游特性变化而非 bug，不会修复

感谢你的反馈 我试验过了 改用其他键位绑定菜单即可正常通过同键位开关 uosc 菜单

我想问一下  uosc 上游特性变化 我去哪里反馈这个问题吗？？uosc 菜单打开时它会强制接管 F1-12 的键位的问题？

**Comment by laodaoxp** [comment]
我把代码[uosc/elements/Menu.lua 修改了
local standalone_keys = {'f1', 'f2', 'f3', 'f4', 'f5', 'f6', 'f7', 'f8', 'f9', 'f10', 'f11', 'f12', {'v', 'ctrl'}}
local standalone_keys = {'f1', 'f2', 'f3', 'f4', 'f5', 'f6',  'f12', {'v', 'ctrl'}}


目前使用正常.哈哈哈  谢谢 
thankyou a lot
thankyou a lot
thankyou a lot
