### ISSUE TITLE
可否整合补帧功能

### ISSUE THREAD

**Issue by zxzxm** [dyphire/mpv-config#12]

**Comment by dyphire** [comment]
个人对补帧和超分这类有一定概率会劣化画面的功能不感兴趣，在可预期的范围内都没有加入此类功能的计划

对于有补帧需求的mpv用户自行集成它并不困难，我并未对此作出限制。仅需参考隔壁[MPV_lazy](https://github.com/hooke007/MPV_lazy)已有的补帧集成方案即可
