### ISSUE TITLE
When the software minimizes the playback of music and switches to the next song, the software switches to the background application

### ISSUE THREAD

**Issue by laodaoxp** [dyphire/mpv-config#122]
开发者你好，十分感谢你的配置包文件。本人一直使用，非常好用。最近发现一个问题 想跟你反馈一下。
包涵以前的版本也有这样的问题：本人使用版本：mpv_config-2024.10.07
Hello developer, thank you very much for the configuration package file. I have been using it all along and it is very user-friendly. I recently discovered a problem and would like to give you feedback.

I am using version: mpc_fig-2024.10.07
Explanation: When playing music files using MPV.exe,
When MPV.exe is played on the front-end desktop, the first song ends and when it jumps to the second song, all functions are normal. The task manager can also see that mpv.exe is the current application.

------------------------------------------------------------------------------------------------------
说明：使用MPV.exe 播放音乐文件的时候，
当MPV.exe 在前台桌面播放的时候，第一手歌曲结束，跳转第二首歌曲的时候，一切功能正常。任务管理器 也可以看到mpv.exe是当前应用。

-When MPV.exe minimizes the desktop and plays a song, the first song ends, and when it jumps to the second song, the software disappears. The MPV software will be transferred to the system backend, and the software cannot be seen running on the desktop. The task manager cannot see mpv.exe, it is only available in the backend application.
At this point, only by manually ending mpv.exe can the software be used normally.

![111 (1)](https://github.com/user-attachments/assets/7dff4c61-eb89-4d28-b818-e5e910dd937d)
![111 (2)](https://github.com/user-attachments/assets/35674eaf-f658-49ff-89d3-8ddac1a0b79e)
视频：video：https://github.com/user-attachments/assets/2effd5d6-1579-4d43-adc1-edd8e8231e94
------------------------------------------------------------------------------------------------------
当MPV.exe 最小化桌面时 播放歌曲的时候，像下面图片有标记①的 这样.，第一手歌曲结束，跳转第二首歌曲的时候，软件会消失。MPV软件会转入系统后台，桌面上看不到软件运行。任务管理器 看不到mpv.exe的，只有后台应用里面才有mpv.exe。
这个时候只有手动结束mpv.exe才可以正常使用软件。﻿

When MPV.exe minimizes the desktop and plays a song, ，Like the one marked with ① in the picture below，the first song ends, and when it jumps to the second song, the software disappears. The MPV software will be transferred to the system backend, and the software cannot be seen running on the desktop. The task manager cannot see mpv.exe, it is only available in the backend application.
At this point, only by manually ending mpv.exe can the software be used normally.

![微信截图_20241013204739](https://github.com/user-attachments/assets/bef4af2a-cd10-4b40-8e3f-f980eceaeeb8)
![222 (1)](https://github.com/user-attachments/assets/b2f45ba5-cf51-4fc8-a0c8-f4fbc4e27c0c)
![222 (2)](https://github.com/user-attachments/assets/1ca9361d-452a-4da4-a683-39f7156c2d69)
视频：video：https://github.com/user-attachments/assets/7d01d40c-4d5c-4bd4-931e-e62a2b0e2d76
------------------------------------------------------------------------------------------------------

If I delete the configuration file: portable_comfig
All normal functions, whether it is front-end playback or software minimized playback, can correctly jump to the next song.
如果我删除配置文件：portable_config
所有功能正常的 不管是前台播放 还是软件最小化播放， 都是可以正确跳转下一首歌曲的。

**Comment by dyphire** [comment]
奇怪的 bug，无法复现

**Comment by laodaoxp** [comment]
I went to my office computer for testing and everything is normal.
This is really a strange bug that cannot be reproduced
It's probably a problem with my computer system

**Comment by laodaoxp** [comment]
> 奇怪的bug，无法恢复

I went to my office computer for testing and everything is normal.
This is really a strange bug that cannot be reproduced
It's probably a problem with my computer system
可以关闭问题了
