### ISSUE TITLE
如何将您的脚本移植到我的mpv-lazy里面

### ISSUE THREAD

**Issue by Simuliya** [dyphire/mpv-config#123]
我对您的某些脚本十分感兴趣，但是我自己已经使用一段时间的mpv-kazy，不想全部转到您这边的软件包，只想要把您的某些脚本移植到我的mpv版本上。但是如剪贴板功能，我将您的脚本文件和脚本配置文件全部放到我的文件里无法运行，后面即使是删除我自己全部的portable_config将您的portable_config全放入也无法实现功能，不知道那边出了问题，但是用您的版本发现可以运行，是portable_config的外部文件需要修改吗？

**Comment by dyphire** [comment]
自定义配置只能自行研究一下了，折腾 mpv 还是要一定的学习能力的
本配置使用的所有脚本的功能及其依赖都已在 [wiki-脚本说明](https://github.com/dyphire/mpv-config/wiki/%E8%84%9A%E6%9C%AC%E8%AF%B4%E6%98%8E) 中说明，可供参考

**Comment by laodaoxp** [comment]
portable_config的外部文件 不需要修改
我都是复制portable_config的外部文件 到MPV里面直接用
