### ISSUE TITLE
关于播放速度有一点疑问

### ISSUE THREAD

**Issue by jiemo9527** [dyphire/mpv-config#128]
为什么设置为0.2X才是实际的1.00x的正常播放速度？求解

**Comment by dyphire** [comment]
无法复现

**Comment by dyphire** [comment]
无其他反馈，关闭

**Comment by jiemo9527** [comment]
与外部多显示器相关，使用自身显示器是正常的。暂不做处理

**Comment by dyphire** [comment]
> 与外部多显示器相关，使用自身显示器是正常的。暂不做处理

奇怪的 bug，我一直在用两台显示器，无法复现此问题
