### ISSUE TITLE
Where can I modify the default volume of 105? thank you!!!

### ISSUE THREAD

**Issue by laodaoxp** [dyphire/mpv-config#129]
Where can I modify the default volume of 105? thank you!!!
请问 默认音量 105 在哪里修改？谢谢！！！
![屏幕截图 2024-11-07 192238](https://github.com/user-attachments/assets/2b6c16d6-f6c6-49a8-904e-6600eebea4f0)

**Comment by dyphire** [comment]
每次通过鼠标滚轮或快捷键更改音量后都会被保存，用同样方式更改即可
如果不想保存全局音量状态可以自行修改配置：https://github.com/dyphire/mpv-config/blob/be26e8e4cafc5350acb46b05430135353b0271d3/script-opts/persist_properties.conf#L2-L3
