### ISSUE TITLE
Windows 11 23H2 22631.4317 HDR video cannot automatically turn on HDR function

### ISSUE THREAD

**Issue by laodaoxp** [dyphire/mpv-config#132]
Windows 11 23H2 22631.4317 HDR video cannot automatically turn on HDR function
The settings are as follows:

gpu-api=vulkan  
#profile=Target 
profile=HDR-PASS 

Previously, setting HDR videos in this way could automatically enable HDR function
System update now:
Windows 11 23H2 22631.4317 also cannot automatically enable HDR functionality
Windows 11 24H2 26100.2161 also cannot automatically enable HDR functionality
<img width="467" alt="屏幕截图 2024-11-08 221715" src="https://github.com/user-attachments/assets/3c0f4c39-ff3d-4d03-a6fe-cab9cdef0a4b">

Windows 11 23H2  22631.4317  HDR视频无法自动开启HDR功能了
设置如下：
gpu-api=vulkan  
#profile=Target 
profile=HDR-PASS ﻿
以前这样设置 HDR视频是可以自动开启HDR功能的.
现在系统更新：
Windows 11 23H2  22631.4317  也不可能自动开启HDR功能
Windows 11 24H2  26100.2161  也不可能自动开启HDR功能
﻿

**Comment by dyphire** [comment]
Ref https://github.com/mpv-player/mpv/issues/15163

**Comment by laodaoxp** [comment]
> 参考[mpv-player/mpv#15163](https://github.com/mpv-player/mpv/issues/15163)

Temporarily resolved
暂时已经解决

Use Nvidia driver 555.85 or later
使用Nvidia 驱动程序 555.85  或更底版本
