### ISSUE TITLE
视频播放不了

### ISSUE THREAD

**Issue by Salted-Fish-Swimming** [dyphire/mpv-config#135]
视频播放不了，一双击就会卡死退出，我用命令行试了试，报错如下，请问如何解决这个问题？

![图片](https://github.com/user-attachments/assets/f2639399-411e-4c1e-abcb-4ce43715cc44)

**Comment by dyphire** [comment]
dup #92
显卡太旧，release 说明都提示了使用此配置需要 GTX 1060 及以上的显卡
