### ISSUE TITLE
 It will be displayed in the upper left corner [webui] v3.0.0 192.168.1.71:8060

### ISSUE THREAD

**Issue by laodaoxp** [dyphire/mpv-config#137]
Play the video every time. It will be displayed in the upper left corner
[webui] v3.0.0
192.168.1.71:8060
May I ask how to cancel?

![屏幕截图 2024-11-30 143939](https://github.com/user-attachments/assets/ccdf4bb3-462b-4c0d-91ab-162c4b8a2c0b)

**Comment by dyphire** [comment]
as @nanachisol  said.

**Comment by laodaoxp** [comment]
> webui] v3.0.0
> 192.168.1.71:8060

thankyou

**Comment by laodaoxp** [comment]
> 作为@nanachisol 说。

thankyou
