### ISSUE TITLE
mpv-file-browser 搜索（ctrl+f）功能失效

### ISSUE THREAD

**Issue by nanachisol** [dyphire/mpv-config#139]
操作步骤
1、TAB打开File-browser扩展
2、CTRL+f（F）调出搜索功能
3、输入后OSD无显示，同时搜索功能也不可用

MPV及配置版本
[mpv_config-2024.11.30](https://github.com/dyphire/mpv-config/releases/tag/mpv_config-2024.11.30)

**Comment by dyphire** [comment]
可以复现。经测试是 mpv 上游的 bug，所有 mp.input 输入响应都出现了问题。使用 https://github.com/zhongfly/mpv-winbuild/releases 的最新构建进行测试仍未修复
