### ISSUE TITLE
如何设置ytdl的视频保存地址

### ISSUE THREAD

**Issue by MiKoto-Railgun** [dyphire/mpv-config#140]
如题，找不到哪里设置保存视频位置，翻了一下ytdl的介绍和ytdl_hook也没发现（PS：极大可能是我眼瞎），求助一下大佬怎么弄

**Comment by dyphire** [comment]
找不到是因为 ytdl_hook 脚本就不支持保存视频，想要下载 ytdl 的视频需要使用另一个脚本，配置见：
https://github.com/dyphire/mpv-config/blob/5bae61cdd890c85708bf2fbd66c99d5dfc51fad7/script-opts/youtube-download.conf#L58-L63

**Comment by MiKoto-Railgun** [comment]
> 找不到是因为 ytdl_hook 脚本就不支持保存视频，想要下载 ytdl 的视频需要使用另一个脚本，配置见：
> 
> https://github.com/dyphire/mpv-config/blob/5bae61cdd890c85708bf2fbd66c99d5dfc51fad7/script-opts/youtube-download.conf#L58-L63
> 
> 
> 仅支持手动下载

哦哦哦，好的谢谢大佬
