### ISSUE TITLE
长按前进一帧异常

### ISSUE THREAD

**Issue by Ho-da-ka** [dyphire/mpv-config#141]
我发现在暂停状态下长按前进一帧时，视频会以正常速度播放，同时osd上显示的当前帧以一定速度增加，长按结束后，osc显示消失，视频会继续播放一会然后暂停，此时的当前帧比长按结束后的当前帧大不少，长按的时间越久，继续播放的时间就会越长，同时额外增加的帧也越多，长按后退一帧就没有这个问题，不过长按后退一帧当前帧减小的速度比长按前进一帧慢不少

**Comment by dyphire** [comment]
> 我发现在暂停状态下长按前进一帧时，视频会以正常速度播放，同时osd上显示的当前帧以一定速度增加

这是 mpv 预期行为，长按前进帧等效为播放有什么问题吗？

> 长按结束后，osc显示消失，视频会继续播放一会然后暂停，此时的当前帧比长按结束后的当前帧大不少，长按的时间越久，继续播放的时间就会越长，同时额外增加的帧也越多，长按后退一帧就没有这个问题，不过长按后退一帧当前帧减小的速度比长按前进一帧慢不少

可以复现，将对应的命令`frame-step;show-text "当前帧：${estimated-frame-number}"`改为`frame-step`后正常。应该是 mpv 上游的 bug，可以在 mpv 上游打开 issue 反馈。由于此为非常规使用，本配置不会去适配

**Comment by Ho-da-ka** [comment]
> 可以复现，将对应的命令`frame-step;show-text "当前帧：${estimated-frame-number}"`改为`frame-step`后正常。应该是 mpv 上游的 bug，可以在 mpv 上游打开 issue 反馈。由于此为非常规使用，本配置不会去适配

我发现在去交错开启的情况下，不修改代码长按前进一帧也不会异常，只是播放的速度大概是0.8倍正常速度，但是长按后退一帧当前帧减小的速度会变得很慢，这个项目对应的mpv 上游是哪个？
