### ISSUE TITLE
快速前进功能不可更改，表现为input.conf中的RIGHT键的值修改了但不生效

### ISSUE THREAD

**Issue by flamesky80** [dyphire/mpv-config#142]
经测试
1、input.conf 中将 RIGHT 的值修改为 seek 1 exact，不生效，按RIGHT键仍然是保持150帧也就是5秒的速度往前快进
2、LEFT 的值有效，修改为 seek -100 exact，可以一次很大幅地后退
3、将SHIFT+RIGHT 修改为 seek 1 exact，有效；甚至把快捷键改成ALT+q，seek 1 exact 也生效

猜测 RIGHT被强行写死 == seek 5 了。

经过测试，将RIGHT键注释掉，按RIGHT键仍然有效，前进5秒。

再经过测试，10月份的release版本也有这个问题。

**Comment by MiKoto-Railgun** [comment]
你到是放上你修改的代码和日志log啊，不然大佬怎么给你看看是怎么回事

**Comment by flamesky80** [comment]
> 你到是放上你修改的代码和日志log啊，不然大佬怎么给你看看是怎么回事
没写完，错按Enter键发早了。

**Comment by MiKoto-Railgun** [comment]
> 经测试 1、input.conf 中将 RIGHT 的值修改为 seek 1 exact，不生效，按RIGHT键仍然是保持150帧也就是5秒的速度往前快进 2、LEFT 的值有效，修改为 seek -100 exact，可以一次很大幅地后退 3、将SHIFT+RIGHT 修改为 seek 1 exact，有效；甚至把快捷键改成ALT+q，seek 1 exact 也生效
> 
> 猜测 RIGHT被强行写死 == seek 5 了。

你把exact去掉试试，精确前进不是按帧率时间计算的

**Comment by flamesky80** [comment]
> > 经测试 1、input.conf 中将 RIGHT 的值修改为 seek 1 exact，不生效，按RIGHT键仍然是保持150帧也就是5秒的速度往前快进 2、LEFT 的值有效，修改为 seek -100 exact，可以一次很大幅地后退 3、将SHIFT+RIGHT 修改为 seek 1 exact，有效；甚至把快捷键改成ALT+q，seek 1 exact 也生效
> > 猜测 RIGHT被强行写死 == seek 5 了。
> 
> 你把exact去掉试试，精确前进不是按帧率时间计算的，它与视频本身有关

我肯定试过（1）有 exact （2）无 exact （3）1、5、10、100 （4）exact 1、5、10、100

你试试，能修改RIGHT键的前进秒数吗？比如  RIGHT seek 100

**Comment by flamesky80** [comment]
> 应该与inputevent扩展有关，你试试同步修改inputevent_key.conf，与input.conf中right数值保值一致。
> 
> `RIGHT seek 5 #event:click`

确实。我把inputevent_key.conf里的RIGHT注释掉，input.conf里的RIGHT就可以任意设置且生效了。
这个inputevent_key.conf 和 input.conf 是什么关系？还有什么其他用吗？

**Comment by dyphire** [comment]
inputevent_key.conf 文件内开头就注释了功能作用的介绍

**Comment by dyphire** [comment]
> > > 应该与inputevent扩展有关，你试试同步修改inputevent_key.conf，与input.conf中right数值保值一致。
> > > `RIGHT seek 5 #event:click`
> > 
> > 
> > 确实。我把inputevent_key.conf里的3项RIGHT 全注释掉，input.conf里的RIGHT就可以任意设置且生效了。 这个inputevent_key.conf 和 input.conf 是什么关系？还有什么其他用吗？
> 
> 个人感觉用处不大，如果不是为了“加载上一次未播放完成的文件”的功能，早就把他精简了。不知道mpv上游什么时候能增添这个功能。 EDIT：还有修正mpv左键双击问题的作用。

可以去 mpv 上游开个 issue 请求添加对长按动作的键绑定支持，mpv 各种键位事件都是有的就是没有开放给键绑定而已。mpv 之前也不支持触控操作，也是近期才添加的

**Comment by flamesky80** [comment]
> 个人感觉用处不大，如果不是为了“加载上一次未播放完成的文件”的功能，早就把他精简了。不知道mpv上游什么时候能增添这个功能。 EDIT：还有修正mpv左键双击问题的作用。

作为小白还以为只需要配置input.conf就可以了，网上一些教程也没提过inputevent_key.conf，没人提醒真抓瞎了。
