### ISSUE TITLE
当播放音乐文件时如何加载指定的一张图片作为封面？

### ISSUE THREAD

**Issue by Trudeau566** [dyphire/mpv-config#144]
下边这样写不行，不知道怎么弄

[封面]
profile-cond=not video
image-file="D:\3.jpg"

**Comment by Trudeau566** [comment]
如下配置貌似解决了
[音乐指定封面]
profile-cond=(filename:match"%.mp3$" or filename:match"%.flac$") ~= nil
profile-restore=copy
audio-display=external-first
cover-art-files=D:\3.jpg

**Comment by MiKoto-Railgun** [comment]
> 如下配置貌似解决了 [音乐指定封面] profile-cond=(filename:match"%.mp3$" or filename:match"%.flac$") ~= nil profile-restore=copy audio-display=external-first cover-art-files=D:\3.jpg

`profile-cond=(aid and not (vid and get("current-tracks/video/albumart")))`

profile-cond改成这个吧，这个更好
这个可以匹配所有音频文件，判断条件是属于音频文件且不包含视频轨道与专辑封面

**Comment by dyphire** [comment]
可以这么做
