### ISSUE TITLE
功能请求：自定义缓存时间和缓存大小，显示缓存速度

### ISSUE THREAD

**Issue by NPCDW** [dyphire/mpv-config#146]
我在 [`tsukimi`](https://github.com/tsukinaha/tsukimi) 上看到可以自定义缓存时间和缓存大小，显示缓存速度，当前项目能否添加

`tsukimi` 也是调用 `mpv` 播放器，但是默认配置对 `windows` 用户不太友好

![image](https://github.com/user-attachments/assets/2369dbef-545d-490c-9364-52b225dd5d12)

![image](https://github.com/user-attachments/assets/85d620bb-2842-43c2-94d0-8c74e8e943ac)

**Comment by dyphire** [comment]
https://github.com/dyphire/mpv-config/blob/d2e55723ac2d44936b8c1f6db21069829cdac5e7/mpv.conf#L124-L125
