### ISSUE TITLE
能请教下发布版本12.04 默认播放视频时比10.07版本亮度低

### ISSUE THREAD

**Issue by cy0o0** [dyphire/mpv-config#148]
如题，请教下大佬该如何解决这个问题

**Comment by dyphire** [comment]
心理作用，无论是本仓库配置还是 mpv 上游都没有进行相关更改

**Comment by cy0o0** [comment]
![image](https://github.com/user-attachments/assets/94e01999-809e-431d-8ffe-f790651a145f)
这个是我在我的电脑上下载两个版本，播放同一视频文件时的截图，左为12.04，右为10.07，应该不是我的心理作用吧。

**Comment by cy0o0** [comment]
我在下载后没有修改任何配置，所以不太清楚如何排查该问题产生原因，大佬能给些建议吗

**Comment by dyphire** [comment]
> ![image](https://private-user-images.githubusercontent.com/52368412/397964890-94e01999-809e-431d-8ffe-f790651a145f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzQ4NjQ3MDMsIm5iZiI6MTczNDg2NDQwMywicGF0aCI6Ii81MjM2ODQxMi8zOTc5NjQ4OTAtOTRlMDE5OTktODA5ZS00MzFkLThmZmUtZjc5MDY1MWExNDVmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMjIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjIyVDEwNDY0M1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTc3ZDgwZjM5NTZiMzNjYWQ5NWY5YjJmZWRjNTlmYWZkYWUxZjViMTExODBlYzk5NTA5MGIxMGRiODc3NTcwMzYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.UbyV7S_pYvGqX9rssO0zFDHB4gLhWaHcOnFlL2EdSCM)
> 这个是我在我的电脑上下载两个版本，播放同一视频文件时的截图，左为12.04，右为10.07，应该不是我的心理作用吧。

无法复现，只能推测可能跟显卡驱动和系统设置有关

**Comment by cy0o0** [comment]
通过替换不同的mpv.exe，测试了一下，应该是mpv的问题，之后版本的mpv不知道为什么在我的环境中就有这个问题。

**Comment by dyphire** [comment]
> 通过替换不同的mpv.exe，测试了一下，应该是mpv的问题，之后版本的mpv不知道为什么在我的环境中就有这个问题。

在你环境中测试的最后一个正常工作的 mpv 版本是哪个？

**Comment by cy0o0** [comment]
https://github.com/dyphire/mpv-winbuild/releases/tag/mpv_own-2024-11-24 我使用该版本及以后会出现该情况

**Comment by dyphire** [comment]
> https://github.com/dyphire/mpv-winbuild/releases/tag/mpv_own-2024-11-24 我使用该版本及以后会出现该情况

推测与此 pr 有关：https://github.com/mpv-player/mpv/pull/15279
你很可能开启了系统 HDR，这是预期效果

**Comment by verygoodlee** [comment]
可以尝试下添加这个选项`target-colorspace-hint=no`，在旧版这本来是默认值的，后来改成yes，然后又改成了auto，

在默认值yes的那段时间我碰到过类似的情况，不过只在HDR视频中有影响，我Windows设置中甚至都没开显示器HDR，选项也生效了，
默认值变为auto后我也一直用的no
