### ISSUE TITLE
English language please

### ISSUE THREAD

**Issue by fossist** [dyphire/mpv-config#15]
Is it possible to add support of english language?
Thank you

**Comment by dyphire** [comment]
Sry so far I have no plan to extend the support of multi-languages.

The initial plan of creating this repo is only to help more people who use chinese as mother language learn about the mpv player and share my own mpv config.

**Comment by Zabooby** [comment]
@dyphire now that uosc supports localised languages how would I go about using english with your config?

**Comment by dyphire** [comment]
> @dyphire now that uosc supports localised languages how would I go about using english with your config?

just set `languages=en` in uosc.conf.
Of course, you also need to have your own input.conf with english.

**Comment by aicynide** [comment]
@dyphire please translate input.conf . You update your config very frequently so provide full english

**Comment by dyphire** [comment]
English localization support has finally been completed and pushed, see https://github.com/dyphire/mpv-config/tree/eng
