### ISSUE TITLE
请问为啥打开文件这个选项会提示错误

### ISSUE THREAD

**Issue by luckylemonade24** [dyphire/mpv-config#151]
drivers
something went wrong. See console for errors.
[uosc] Subprocess failed: init
[uosc] Couldn't open drivers. Error: nil
我是新下的12.04版本默认配置

**Comment by luckylemonade24** [comment]
![Uploading {4AE19E88-E294-4986-B003-B47093E6D541}.png…]()

**Comment by luckylemonade24** [comment]
<img width="726" alt="{4AE19E88-E294-4986-B003-B47093E6D541}" src="https://github.com/user-attachments/assets/15e44893-7281-422c-9de5-50b100af88a1" />

**Comment by dyphire** [comment]
dup #143
