### ISSUE TITLE
字幕重复问题，疑似fuzzydir.lua脚本出现冲突

### ISSUE THREAD

**Issue by MiKoto-Railgun** [dyphire/mpv-config#154]
![image](https://github.com/user-attachments/assets/63d4b0da-ef6d-4be2-881b-57f627312b69)

如图，会显示重复字幕轨道，原本只会显示sc与tc两个轨道，结果多了两个

![image](https://github.com/user-attachments/assets/aa655dc9-c295-46c1-853b-6b2120e5031d)

原因是因为我喜欢将字幕统一放进sub文件夹里，后面经过排查是mpv(还是uosc？)与fuzzydir.lua脚本出现了冲突

mpv貌似会自动读取sub与subs文件夹查找是否有字幕，而fuzzydir.lua也是查找文件夹里的字幕（但它可以查找视频目录下里的任意文件夹是否含有字幕，并可以自定义检索深度及文件夹层级），脚本却会将字幕继续添加进字幕轨道，从而造成字幕轨道重复。

而把字幕所在文件夹重命名成其他名字就可以规避此类错误了，因为mpv无法检查到其他命名文件夹里的字幕，fuzzydir.lua脚本则可以继续检索添加字幕轨，若把脚本也删了，则其他命名文件夹里的字幕也无法添加视频里了。

所以我想，fuzzydir.lua若是能避开mpv会检索的字幕文件夹不添加其里面的字幕，又或是能读取字幕轨里存在相同文件夹名就不添加，这样视频观看体验会更好。

（PS：我不知道配置文件里的excluded_dir是否能规避此类错误，但我试了一下没有起效。）

**Comment by dyphire** [comment]
问题出在 Windows 系统文件名不区分大小写，而脚本 fuzzydir.lua 未进行处理。修复
