### ISSUE TITLE
窗口最大化，或者Ctrl + 放大窗口之后，视频就会卡顿掉帧

### ISSUE THREAD

**Issue by winteboo** [dyphire/mpv-config#155]
窗口最大化，或者Ctrl + 放大窗口之后，视频会卡顿掉帧，但是Ctrl - 不会

**Comment by winteboo** [comment]
啊，可是我是4080笔记本🤔️

> 大概率是因为显卡性能不够。

**Comment by dyphire** [comment]
最大化和全屏播放下渲染分辨率会变，就是缩放窗口一样会变。跟你视频无关，和显示器分辨率和窗口大小有关
会卡就是渲染性能不够，4080都卡是因为你没为mpv指定独显渲染，系统默认核显渲染

**Comment by winteboo** [comment]
> > > 大概率是因为显卡性能不够。
> > 
> > 
> > 啊，可是我是4080笔记本🤔️，然后视频多大也不会卡，但是只要一放大窗口，就会卡
> 
> mpv是调用独立显卡吗 https://www.asus.com.cn/support/faq/1044213/
我查看了一下不是，使用的13700HX的32EU，我把shader清空了就不卡了

**Comment by winteboo** [comment]
> 最大化和全屏播放下渲染分辨率会变，就是缩放窗口一样会变。跟你视频无关，和显示器分辨率和窗口大小有关
> 会卡就是渲染性能不够，4080都卡是因为你没为mpv指定独显渲染，系统默认核显渲染

但是我觉得应该还是和显卡没太大关系，因为比如我放一个720p的视频和2k的视频，只要不放大窗口，都不会卡，但是720p放大到2k（屏幕是2k）就会开始卡
