### ISSUE TITLE
webp动图创建失败，请问为什么乱码了。。

### ISSUE THREAD

**Issue by 1234meat** [dyphire/mpv-config#17]
![image](https://user-images.githubusercontent.com/103420806/214426608-8dd39279-b83c-4c22-882b-5a4e95d0a672.png)

**Comment by dyphire** [comment]
仔细看了眼报错信息，提示未找到ffmpeg。请确保你有正确配置ffmpeg环境变量或路径

**Comment by 1234meat** [comment]
ffmpeg确实在path, cmd直接输入ffmpeg会返回结果
[mpv.log](https://github.com/dyphire/mpv-config/files/10496354/mpv.log)

**Comment by dyphire** [comment]
> 1 ffmpeg确实在path, cmd直接输入ffmpeg会返回结果 2 是本地的视频。 日志的话，抱歉不知道具体该粘贴哪一部分，就都放上来了。。级别应该是info. 麻烦大佬查看一下了 [mpv.log](https://github.com/dyphire/mpv-config/files/10496354/mpv.log)

奇怪了，看日志我也没看出有什么问题。是所有视频都不能创建webp动图吗？

https://github.com/dyphire/mpv-config/blob/5af8f89d0508504a9fd505ccbccfb2f0ac9070f2/scripts/mpv-webp.lua#L175-L176

将`-loglevel error`改为`-loglevel debug`后重新测试上传日志文件

**Comment by 1234meat** [comment]
[mpv.log](https://github.com/dyphire/mpv-config/files/10498671/mpv.log)
改为debug. 又测试了一下，好了？。。难道是因为下午我把mpv.net_cm的部分包直接挪到了文件夹里??...（因为想加一个mvtool倍帧滤镜，不会整，一开始是失效的，我觉得可能是缺脚本里定义的vs/python便携包，就用笨办法把mpv.net_cm的所有包都复制到了mpv_config-2023.01.22文件夹里（没有任何文件替换），mvtools倍帧就生效了。
刚一测试，居然webp也能正常截取了。。
另外我发现这种animated webp和qq聊天的兼容性不是太好，发进去别人是看不到动作效果。。请问怎么改成截取GIF
ptp/z4a图床倒是支持，bbcode挂到论坛里也能正常看到动画效果。
![2023-01-25_19-02-25](https://user-images.githubusercontent.com/103420806/214548829-deca0629-715c-40d9-b05b-7f490b6adab3.png)
不过现在还有一个小问题，每次打开一个新文件，就会出现一个这个东西，我也不知道是干嘛的，怎么关掉。。

**Comment by dyphire** [comment]
> 另外我发现这种animated webp和qq聊天的兼容性不是太好，发进去别人是看不到动作效果。。
请问怎么改成截取GIF/定义分辨率等参数。。

可以参考[mpv-gif.lua](https://github.com/the-honey/mpv-gif-generator/blob/master/mpv-gif.lua)脚本的代码修改下即可截取gif动图，但我个人不推荐，同片段gif的大小要远超webp格式，不是几倍的差距那么简单。

>  ![2023-01-25_19-02-25](https://user-images.githubusercontent.com/103420806/214548829-deca0629-715c-40d9-b05b-7f490b6adab3.png) 
不过现在还有一个小问题，每次打开一个新文件，就会出现一个这个东西，我也不知道是干嘛的，怎么关掉。。

这是[history-bookmark.lua](https://github.com/dyphire/mpv-config/blob/master/scripts/history-bookmark.lua)脚本的功能，它会记录每个文件夹最后播放的文件，当播放同目录下其他文件时会提示是否恢复上次播放记录。如不需要可以在对应的`history_bookmark.conf`中禁用`enabled`

**Comment by 1234meat** [comment]
又失效了。。什么都没改
```
[ 331.055][d][cplayer] Run command: script-message, flags=73, args=[args="set_webp_start"]
[ 332.255][d][cplayer] Run command: script-message, flags=73, args=[args="set_webp_end"]
[ 333.887][d][cplayer] Run command: script-message, flags=73, args=[args="make_webp_with_subtitles"]
[ 333.887][i][mpv_webp] Creating webP. 
[ 333.887][d][cplayer] Run command: subprocess, flags=64, args=[args="powershell,-NoProfile,-Command,ffmpeg -y -hide_banner -loglevel debug -ss 730.521 -copyts -t 1.168 -i 'G:\\剧\\Why.Women.Kill.S01.1080p.BluRay.REMUX.AVC.DTS-HD.MA.5.1-CBE\\Why.Women.Kill.S01E04.You.Had.Me.at.Homicide.1080p.BluRay.REMUX.AVC.DTS-HD.MA.5.1-CBE.mkv' -lavfi fps=24,zscale='trunc(ih*dar/2)*2:trunc(ih/2)*2':f=spline36,setsar=1/1,zscale=1280:-1:f=spline36,subtitles='G\\\\:/剧/Why.Women.Kill.S01.1080p.BluRay.REMUX.AVC.DTS-HD.MA.5.1-CBE/Why.Women.Kill.S01E04.You.Had.Me.at.Homicide.1080p.BluRay.REMUX.AVC.DTS-HD.MA.5.1-CBE.mkv':si=1 -lossless 0 -q:v 85 -compression_level 3 -loop 0 'C:/Users/Administator/Desktop/mpv_config-2023.01.22/portable_config/files/webp/Why.Women.Kill.S01E04.You.Had.Me.at.Homicide.1080p.BluRay.REMUX.AVC.DTS-HD.MA.5.1-CBE_000.webp'", playback_only="no", capture_size="67108864", capture_stdout="yes", capture_stderr="no", detach="no", env="", stdin_data="", passthrough_stdin="no"]
[ 334.212][e][mpv_webp] ffmpeg : Ξ·¨½«¡°ffmpeg¡±Ϯʶ±ퟺ�cmdlet¡¢º¯ʽ¡¢½ű¾΄¼þ»򿉔ːг̐򵄃û³ơ£ǫ¼첩û³ƵĆ´д£¬ȧ¹û°üÀ¨·¾¶£¬ǫȷ±£·¾¶սȷ£¬
[ 334.213][e][mpv_webp] Ȼº󔙊Ԓ»´Ρ£
[ 334.213][e][mpv_webp] ˹Ԛλփ А:1 ז·û: 1
[ 334.213][e][mpv_webp] + ffmpeg -y -hide_banner -loglevel debug -ss 730.521 -copyts -t 1.168 - ...
[ 334.213][e][mpv_webp] + ~~~~~~
[ 334.213][e][mpv_webp]     + CategoryInfo          : ObjectNotFound: (ffmpeg:String) [], CommandNotFoundException
[ 334.213][e][mpv_webp]     + FullyQualifiedErrorId : CommandNotFoundException
[ 334.213][e][mpv_webp]  
[ 334.225][i][mpv_webp] Failed to creat webP. 
```
