### ISSUE TITLE
mpv.conf中截图模板文件名参数有冗余

### ISSUE THREAD

**Issue by 1234meat** [dyphire/mpv-config#18]
conf中截图模板原始参数有冗余，会导致出现多余字段
![image](https://user-images.githubusercontent.com/103420806/214568453-f6e20014-381e-4aaf-9dc0-76e4312d970c.png)
我修改了一下。（路径改成桌面的时候发现的这个bug）
![image](https://user-images.githubusercontent.com/103420806/214568241-6c8a0872-429b-419a-af03-776075414387.png)
重启mpv, 再次截图，现在后缀正常了
![image](https://user-images.githubusercontent.com/103420806/214568917-428dd03d-4ae5-4353-ad79-b48313dcc8cf.png)

**Comment by dyphire** [comment]
由 https://github.com/dyphire/mpv-config/commit/b583d5f7c692a5142003bf5d2ada6f9f759091ea 修复
