### ISSUE TITLE
求一个截取gif的脚本兼容支持

### ISSUE THREAD

**Issue by 1234meat** [dyphire/mpv-config#19]
#17 
大佬，试了一晚上，您给我的gif lua截不出来gif。。看了一下，发现他的仓库全是待修的issue。。
webp压缩率是好，可是我分享出去，这个格式过于先进，兼容性太差了，手机上看不到。。。我手机上的app试了个便，都打不开这种animated webp. 我对清晰度没啥要求，就是希望内容能分享出去
所以基于分享和兼容性的方面，可以麻烦您集成一个gif脚本吗

**Comment by 1234meat** [comment]
[  16.201][d][cplayer] Run command: script-binding, flags=73, args=[name="mpv_gif/set_gif_start"]
[  16.351][d][cplayer] Run command: script-binding, flags=73, args=[name="mpv_gif/set_gif_start"]
[  16.768][v][auto_profiles] Re-evaluating auto profile video-sync 
[  16.852][v][auto_profiles] Re-evaluating auto profile video-sync 
[  16.976][v][auto_profiles] Re-evaluating auto profile video-sync 
[  17.101][v][auto_profiles] Re-evaluating auto profile video-sync 
[  17.268][v][auto_profiles] Re-evaluating auto profile video-sync 
[  17.477][v][auto_profiles] Re-evaluating auto profile video-sync 
[  17.727][v][auto_profiles] Re-evaluating auto profile video-sync 
[  17.943][d][cplayer] Run command: script-binding, flags=73, args=[name="mpv_gif/set_gif_end"]
[  18.079][d][cplayer] Run command: script-binding, flags=73, args=[name="mpv_gif/set_gif_end"]
[  18.226][v][auto_profiles] Re-evaluating auto profile video-sync 
[  18.643][v][auto_profiles] Re-evaluating auto profile video-sync 
[  18.679][d][cplayer] Run command: script-binding, flags=73, args=[name="inputevent/@SPACE"]
[  18.799][d][cplayer] Run command: script-binding, flags=73, args=[name="inputevent/@SPACE"]
[  18.799][v][inputevent] Evaluating event: click 
[  18.799][v][inputevent] Evaluating comand: script-binding simplehistory/history-load-last 
[  18.799][v][inputevent] Evaluating comand: cycle pause 
[  18.799][v][inputevent] Apply comand: cycle pause 
[  18.799][d][cplayer] Run command: cycle, flags=73, args=[name="pause", value="1.000000"]
[  18.799][v][cplayer] Set property: pause -> 1
[  18.799][d][ao/wasapi] Thread Reset
[  18.803][v][auto_profiles] Re-evaluating auto profile pause 
[  18.803][i][auto_profiles] Applying auto profile: pause 
[  18.803][i][dynamic_crop] Meta Stats: 
[  18.803][i][dynamic_crop] Limit - min/max: 26/26 | counter: 0 
[  18.803][i][dynamic_crop] Trusted - unique: 1 | offset: X:0 Y:0  
[  18.803][i][dynamic_crop] \ w=1920:h=1080:x=0:y=0         | offX=  0 offY=  0 | applied=1 overall=0 last_seen=0 
[  18.803][i][dynamic_crop] Buffer - unique: 0 | total: 0 0sec | known_ratio: 0 0sec 
[  18.803][d][cplayer] Run command: apply-profile, flags=64, args=[name="pause", mode="apply"]
[  18.803][v][cplayer] Applying profile 'pause'...
[  18.803][v][cplayer] Setting option 'ontop' = 'no' (flags = 4)
[  18.804][d][cplayer] Run command: write-watch-later-config, flags=73, args=[]
[  18.804][d][global] config path: 'C:/mpv_config-2023.01.22/portable_config/cache/watch_later' -> 'C:/mpv_config-2023.01.22/portable_config/cache/watch_later'
[  18.804][i][cplayer] Saving state.
[  18.810][v][vo/gpu-next] Window size: 1344x756 (Borders: l=0 t=0 r=0 b=0)
[  18.810][v][vo/gpu-next] Video source: 1920x1080 (1:1)
[  18.810][v][vo/gpu-next] Video display: (0, 0) 1920x1080 -> (0, 0) 1344x756
[  18.810][v][vo/gpu-next] Video scale: 0.700000/0.700000
[  18.810][v][vo/gpu-next] OSD borders: l=0 t=0 r=0 b=0
[  18.810][v][vo/gpu-next] Video borders: l=0 t=0 r=0 b=0
[  18.810][v][vo/gpu-next] Window size: 1344x756 (Borders: l=0 t=0 r=0 b=0)
[  18.810][v][vo/gpu-next] Video source: 1920x1080 (1:1)
[  18.810][v][vo/gpu-next] Video display: (0, 0) 1920x1080 -> (0, 0) 1344x756
[  18.810][v][vo/gpu-next] Video scale: 0.700000/0.700000
[  18.810][v][vo/gpu-next] OSD borders: l=0 t=0 r=0 b=0
[  18.810][v][vo/gpu-next] Video borders: l=0 t=0 r=0 b=0
[  22.607][d][cplayer] Run command: script-binding, flags=73, args=[name="mpv_gif/make_gif"]
[  22.607][i][mpv_gif] Creating gif. 
[  22.607][d][osd/libass] ASS library version: 0x1700000 (runtime 0x1700000)
[  22.607][v][osd/libass] libass API version: 0x1700000
[  22.607][v][osd/libass] libass source: commit: 0.17.0-25-g9995c9741d3faf66a82f8ca90668ef681cf7b022
[  22.608][v][osd/libass] Shaper: FriBidi 1.0.12 (SIMPLE) HarfBuzz-ng 6.0.0 (COMPLEX)
[  22.608][d][global] config path: 'subfont.ttf' -/-> 'C:/mpv_config-2023.01.22/portable_config/subfont.ttf'
[  22.608][d][global] config path: 'fonts.conf' -> 'C:/mpv_config-2023.01.22/portable_config/fonts.conf'
[  22.608][d][global] config path: 'fonts' -> 'C:/mpv_config-2023.01.22/portable_config/fonts'
[  22.608][d][global] user path: '~~/fonts' -> 'C:/mpv_config-2023.01.22/portable_config/fonts'
[  22.608][v][osd/libass] Setting up fonts...
[  22.609][v][osd/libass] Loading font file 'C:/mpv_config-2023.01.22/portable_config/fonts\Material-Design-Iconic-Font.ttf'
[  22.609][v][osd/libass] Loading font file 'C:/mpv_config-2023.01.22/portable_config/fonts\MaterialIconsRound-Regular.otf'
[  22.609][v][osd/libass] Loading font file 'C:/mpv_config-2023.01.22/portable_config/fonts\modernx-osc-icon.ttf'
[  22.609][v][osd/libass] Loading font file 'C:/mpv_config-2023.01.22/portable_config/fonts\NotoSansCJK-Bold.ttc'
[  22.618][v][osd/libass] Loading font file 'C:/mpv_config-2023.01.22/portable_config/fonts\NotoSerifCJK-Bold.ttc'
[  22.632][v][osd/libass] Loading font file 'C:/mpv_config-2023.01.22/portable_config/fonts\uosc_textures.ttf'
[  22.637][v][osd/libass] Using font provider directwrite (with GDI)
[  22.637][v][osd/libass] Done.
[  22.637][d][cplayer] Run command: subprocess, flags=64, args=[args="powershell,-NoProfile,-Command,ffmpeg -y -hide_banner -loglevel debug -ss 1781.375  -t 1.75 -i 'G:\\DEMUX\\The Father 2020\\GBR.mkv' -lavfi fps=15,zscale='trunc(ih*dar/2)*2:trunc(ih/2)*2':f=spline36,setsar=1/1,zscale=240:-1:f=spline36 -lossless nil -q:v nil -compression_level nil -loop 0 'C:\\Users\\Administator\\Desktop/GBR_000.gif'", playback_only="no", capture_size="67108864", capture_stdout="yes", capture_stderr="no", detach="no", env="", stdin_data="", passthrough_stdin="no"]
[  22.638][v][osd/libass] fontselect: (等线, 400, 0) -> DengXian, 0, DengXian
[  22.799][d][cplayer] Run command: script-binding, flags=73, args=[name="mpv_gif/make_gif"]
[  22.882][e][mpv_gif] ffmpeg : Ξ·¨½«¡°ffmpeg¡±Ϯʶ±ퟺ�cmdlet¡¢º¯ʽ¡¢½ű¾΄¼þ»򿉔ːг̐򵄃û³ơ£ǫ¼첩û³ƵĆ´д£¬ȧ¹û°üÀ¨·¾¶£¬ǫȷ±£·¾¶սȷ£¬
[  22.882][e][mpv_gif] Ȼº󔙊Ԓ»´Ρ£
[  22.882][e][mpv_gif] ˹Ԛλփ А:1 ז·û: 1
[  22.882][e][mpv_gif] + ffmpeg -y -hide_banner -loglevel debug -ss 1781.375  -t 1.75 -i 'G:\D ...
[  22.882][e][mpv_gif] + ~~~~~~
[  22.882][e][mpv_gif]     + CategoryInfo          : ObjectNotFound: (ffmpeg:String) [], CommandNotFoundException
[  22.882][e][mpv_gif]     + FullyQualifiedErrorId : CommandNotFoundException
[  22.882][e][mpv_gif]  
[  22.896][i][mpv_gif] Failed to creat gif. 
[  22.897][d][vo/gpu-next/libplacebo] (Re)creating 490x195x0 texture with format r8
[  23.232][d][cplayer] Run command: disable-section, flags=64, args=[name="mbtn_left"]
[  23.232][d][cplayer] Run command: disable-section, flags=64, args=[name="wheel"]
[  23.236][d][cplayer] Run command: disable-section, flags=64, args=[name="mbtn_left"]
[  23.236][d][cplayer] Run command: disable-section, flags=64, args=[name="wheel"]

**Comment by 1234meat** [comment]
另外关于webp.conf, 我无法更改任何输出目录，一改就会出错。。

**Comment by dyphire** [comment]
> #17 大佬，试了一晚上，您给我的gif lua截不出来gif。。看了一下，发现他的仓库全是待修的issue。。 webp压缩率是好，可是我分享出去，这个格式过于先进，兼容性太差了，手机上看不到。。。我手机上的app试了个便，都打不开这种animated webp. 我对清晰度没啥要求，就是希望内容能分享出去 所以基于分享和兼容性的方面，可以麻烦您集成一个gif脚本吗

我个人没有使用gif的需求，所以不会考虑集成。不过我之前的意思不是让你用mpv-gif.lua那个脚本，而是参考它的ffmpeg相关代码修改下webp中的ffmpeg代码后使用，需要修改的地方应该就两三处，可以自己研究下，不难。

> 另外关于webp.conf, 我无法更改任何输出目录，一改就会出错，不能正常生成webp。。

不清楚你的魔改哪里有问题，无法复现

**Comment by dyphire** [comment]
> 我个人没有使用gif的需求，所以不会考虑集成。不过我之前的意思不是让你用mpv-gif.lua那个脚本，而是参考它的ffmpeg相关代码修改下webp中的ffmpeg代码后使用，需要修改的地方应该就两三处，可以自己研究下，不难。

放一个最简单的修改实现补丁：
```diff
---
 scripts/mpv-webp.lua | 4 ++--
 1 file changed, 2 insertions(+), 2 deletions(-)

diff --git a/scripts/mpv-webp.lua b/scripts/mpv-webp.lua
index 0219637..a5417f9 100644
--- a/scripts/mpv-webp.lua
+++ b/scripts/mpv-webp.lua
@@ -155,7 +155,7 @@ function make_webp_internal(burn_subtitles)
 
     -- increment filename
     for i = 0, 999 do
-        local fn = string.format('%s_%03d.webp', file_path, i)
+        local fn = string.format('%s_%03d.gif', file_path, i)
         if not file_exists(fn) then
             webpname = fn
             break
@@ -172,7 +172,7 @@ function make_webp_internal(burn_subtitles)
         copyts = "-copyts"
     end
 
-    cmd = string.format("%s -y -hide_banner -loglevel error -ss %s %s -t %s -i '%s' -lavfi %s -lossless %s -q:v %s -compression_level %s -loop %s '%s'", options.ffmpeg_path, position, copyts, duration, pathname, trim_filters, options.lossless, options.quality, options.compression_level, options.loop, webpname)
+    cmd = string.format("%s -y -hide_banner -loglevel error -ss %s %s -t %s -i '%s' -lavfi 'split[s0][s1];[s0]palettegen[p];[s1][p]paletteuse',%s '%s'", options.ffmpeg_path, position, copyts, duration, pathname, trim_filters, webpname)
     args =  { 'powershell', '-NoProfile', '-Command', cmd }
     local screenx, screeny, aspect = mp.get_osd_size()
     mp.set_osd_ass(screenx, screeny, "{\\an9}● ")
-- 
```
应用以上更改后即可正常创建gif动图，脚本中的冗余选项和webp→gif的命名更改请自行操作
