### ISSUE TITLE
如何关闭.mpv.history文件的生成

### ISSUE THREAD

**Issue by FanJZSS** [dyphire/mpv-config#2]
每次播放完成后关闭播放器都会产生.mpv.history文件，请问该如何设置才能不生成这个文件？

**Comment by dyphire** [comment]
这是[history-bookmark.lua](https://github.com/dyphire/mpv-config/blob/master/scripts/history-bookmark.lua)的脚本功能，它可以记录并恢复视频目录的上次播放记录（播放同目录其他文件时可通过快捷键确认是否恢复该目录上次播放进度; 配置文件[history_bookmark.conf](https://github.com/dyphire/mpv-config/blob/master/script-opts/history_bookmark.conf)）。

目前该脚本只能通过在视频目录下生成.mpv.history文件的方式工作，暂无更优雅的解决方案。可以在配置文件里设置相关行为，我已优化此脚本功能，现在默认禁用
