### ISSUE TITLE
调用mpv播放b站部分视频，音频出现诡异声音

### ISSUE THREAD

**Issue by 1234meat** [dyphire/mpv-config#20]
https://www.bilibili.com/video/BV1Mx4y137fa/?vd_source=8fcfe20baf14e7b64e350c3d4241af2f
使用脚本Play-With-MPV：https://github.com/LuckyPuppy514/Play-With-MPV
使用的是tampermonkey，目前仅在这一个视频发现声音有问题？。。。

**Comment by dyphire** [comment]
这个问题我其实爱莫能助。1. 我实际上不使用mpv播放网络视频，所以这方面研究不深。2. 你之前提到增加了补帧的类似功能集成，我无法复现你的使用环境并定位问题的可能性。


当然，你也可以尝试在命令行终端输入`mpv --no-config url`来测试纯净模式下是否出现问题，如果会出现则是mpv本身问题建议向mpv报告，如果正常则慢慢排查你增加的东西是否有影响，再之后排查是否是mpv.conf中某些参数的影响

直觉上我怀疑是vf/af音视频滤镜方面出了问题

**Comment by 1234meat** [comment]
没使用任何滤镜。。参数也没改。。我去官方下面问问吧
