### ISSUE TITLE
[Feature Request]: Integrate youtube-download.lua with uosc's menus

### ISSUE THREAD

**Issue by NaiveInvestigator** [dyphire/mpv-config#21]
Integrate youtube-download.lua with uosc's menus similiar to this script.
https://github.com/christoph-heinrich/mpv-quality-menu

I think it would an awesome feature to have. I hope you consider it!

**Comment by dyphire** [comment]
The source repository for this script: https://github.com/cvzi/mpv-youtube-download
You should open the issue tracker there to request this function
