### ISSUE TITLE
how can I add external audio/Subtitle from URL

### ISSUE THREAD

**Issue by aicynide** [dyphire/mpv-config#24]

**Comment by dyphire** [comment]
You can can achieve this through by [sub-add](https://[mpv.io](https://mpv.io/manual/master/#command-interface-sub-add)/manual/master/#command-interface-sub-add) and [audio-add](https://[mpv.io](https://mpv.io/manual/master/#command-interface-audio-add)/manual/master/#command-interface-audio-add) command.
