### ISSUE TITLE
Current Situation of English Support

### ISSUE THREAD

**Issue by dyphire** [dyphire/mpv-config#34]
Ref https://github.com/dyphire/mpv-config/discussions/33#discussioncomment-6956347

English support has always been on my plan list. But currently, less than 50% of the progress has been completed, and a large number of configuration files need to be translated, resulting in slow progress.
![image](https://github.com/dyphire/mpv-config/assets/61936050/a5a6f63f-0816-44e5-80fb-4b878c935288)
![image](https://github.com/dyphire/mpv-config/assets/61936050/74fe1a68-4a00-43db-a92b-7edb284d2b59)
![image](https://github.com/dyphire/mpv-config/assets/61936050/5f442803-7276-42fb-816c-1053af44dc49)

But due to @aicynide malicious slander, this plan will be put on hold indefinitely.

**Comment by Zabooby** [comment]
Yup it's annoying to see people constantly ask you and @hooke007 to translate to English when they themselves can translate the entire repo by simply using the google translate extension. 

Regarding your efforts to support English natively, what method are you currently  using to translate files? 

When I compare/test both yours and @hooke007's configs I use the [google translate website](https://translate.google.co.uk/?sl=auto&tl=en&op=docs) to translate any files I want to read in English. It works well but iirc it can cause some formatting issues and files first need to be converted to `.docx`. 

Maybe this could help speed up the process?

**Comment by dyphire** [comment]
> Yup it's annoying to see people constantly ask you and @hooke007 to translate to English when they themselves can translate the entire repo by simply using the google translate extension.
> 
> Regarding your efforts to support English natively, what method are you currently using to translate files?

I use this extension of [vscode-google-translate](https://marketplace.visualstudio.com/items?itemName=funkyremi.vscode-google-translate) in vscode for translation.

It actually works well, and currently only the comments in the configuration files in the `script-opts` directory have not been translated yet. 
But I am unwilling to serve users like  @aicynide, so English support will be put on hold.

**Comment by dyphire** [comment]
> Why don't you use chatgpt, imo it would be better than google translate.

Due to can't use the numbers of Chinese region or google voice to register  chatgpt, it is not possible to use the OpenAI-key for translation unless someone is willing to provide it.

> This aicynide guy may be a pro English, I agree, but remember why you put this repo on GitHub in the first place, you want to share your work with millions of people on GitHub, and to get that outreach you "need" to use English

As I mentioned there: https://github.com/dyphire/mpv-config/issues/15#issuecomment-1319500209

> The initial plan of creating this repo is only to help more people who use chinese as mother language learn about the mpv player and share my own mpv config.

This project was initially aimed at Chinese users, and at the same time, I have other open source projects in English primarily aimed at more users. Are all public projects on Github aimed at English users? In fact, to my knowledge, there are a large number of non English projects. So I cannot accept this kind of bandit logic.

The reason why I added English support to the to-do list is mainly because the methods mentioned https://github.com/dyphire/mpv-config/issues/16#issuecomment-1384363395 are no longer available.
Considering that there are also some English users who believe this project is useful to them, I have added English localization support to the to-do list and are gradually implementing it.

**Comment by oplyt** [comment]
Are you by in any way paid by Chinkese Communist Party which is responsible for killing 200 millions of Innocent people and torturing its own countless citizens
Will you kill me if i say winnie the pooh?

**Comment by dyphire** [comment]
After spending a period of vacation, I adjusted my mood and used my free time to complete English localization support. 
Prepare to push it after making some adjustments.

**Comment by dyphire** [comment]
English localization support has finally been completed and pushed, see https://github.com/dyphire/mpv-config/tree/eng

**Note**: It should be pointed out that the English branch is difficult to actively maintain. Because I personally do not use it, it increases maintenance costs. This requires other people who will use it in the future to spontaneously maintain and open PR, if any.
