### ISSUE TITLE
关于追加读取指定的配置文件include=的问题

### ISSUE THREAD

**Issue by FanJZSS** [dyphire/mpv-config#4]
我目前在用您的mpv.net，在mpv.conf设置了一条include = '~~/config/mpvown.conf'，在mpv.conf编辑器中有提到这条参数必须位于主配置mpv.conf中的末尾，避免追加配置被覆盖

但是我测试时发现无论include = '~~/config/mpvown.conf'这条参数在mpv.conf首位或末尾，播放器似乎只会加载mpvown.conf里的参数

我是用sub-font设置字幕缺省字体来测试的，无论我在mpv.conf里设置的缺省字体是什么，播放器只会加载mpvown.conf里设置的缺省字体

**Comment by dyphire** [comment]
理论上不可能，请上传日志文件

**Comment by dyphire** [comment]
https://github.com/dyphire/mpv.net/actions/runs/2436356233
![](https://cdn.jsdelivr.net/gh/dyphire/PicGo/img/2022/06/04/20220604022122.png)
修正include参数相关说明
