### ISSUE TITLE
secondary-sub-override=no功能失效

### ISSUE THREAD

**Issue by Huizs** [dyphire/mpv-config#43]
我平时有用次字幕来加载ass弹幕，更新了[mpv_config-2023.12.03]后secondary-sub-override=no选项功能失效，启用无法渲染和主字幕使用相同的字幕渲染逻辑，我在你构建的MPV_OWN中查找替换版本测试，从[MPV_OWN 2023-11-05 08:41](https://github.com/dyphire/mpv-winbuild/releases/tag/mpv_own-2023-11-05)之后的11-06开始的版本都失效了

**Comment by dyphire** [comment]
感谢报告错误，由于 mpv 上游某次提交导致修改版 rebase 时丢失部分内容，加上我个人并不使用该功能以致于一直未能发现错误。
由 https://github.com/dyphire/mpv/commit/b5131db4e2920196c4f17bd38e7ae2d7d1af8cbb 提交修复，并重新打包发布

**Comment by dyphire** [comment]
提醒：相关修改已优化实现并合并至 mpv 上游：https://github.com/mpv-player/mpv/commit/b563b2aed0aaca7a51ffe40e0e923c00fd77de46 ，之后不再需要修改版了。选项名称和行为有所变化

**Comment by Huizs** [comment]
> 提醒：相关修改已优化实现并合并至 mpv 上游：[mpv-player/mpv@b563b2a](https://github.com/mpv-player/mpv/commit/b563b2aed0aaca7a51ffe40e0e923c00fd77de46) ，之后不再需要修改版了。选项名称和行为有所变化

好的，牛啊
