### ISSUE TITLE
如何开启mpv的log

### ISSUE THREAD

**Issue by Naylor55** [dyphire/mpv-config#44]

**Comment by Naylor55** [comment]
在初始化（MpvRenderContextCreate）的时候程序崩溃了，现在想收集一下mpv的log排查原因

**Comment by dyphire** [comment]
默认就启用了日志功能：
https://github.com/dyphire/mpv-config/blob/884d53d562059b3f3dc98ac8745be3cad2e1424e/mpv.conf#L92
自己查看下 files 文件夹下的日志文件吧
