### ISSUE TITLE
console如何实现中文切换并输入

### ISSUE THREAD

**Issue by 0915xiaoxiang** [dyphire/mpv-config#45]
window 10 22H2 19045.3693
mpv 0.37.0
场景：添加中文章节名

想问下大佬，chapter_make_read.lua是如何实现在console里进行中文切换并输入中文章节名的，脚本内容好像并没有体现
user-input-module.lua和user-input.lua也没有改动

**Comment by dyphire** [comment]
这跟脚本没关系，只要你使用的 mpv 是包含上游实现 IME的 PR https://github.com/mpv-player/mpv/pull/13104 编译的就可以切换中文输入。
相应的 mpv 可以自己编译或者在 https://github.com/dyphire/mpv-winbuild/releases 下载
