### ISSUE TITLE
d3d12va-copy最低系统要求？

### ISSUE THREAD

**Issue by nanachisol** [dyphire/mpv-config#46]
d3d12va-copy在我的系统上使用，会回退到软件解码。当然这是因为我的平台硬件过于陈旧，请问作者d3d12va-copy最低系统要求是什么？方便以后升级硬件。多谢！

[   8.074][v][vd] Looking at hwdec h264-d3d12va-copy...
[   8.075][w][ffmpeg] av_log callback called with bad parameters (NULL AVClass).
[   8.075][w][ffmpeg] This is a bug in one of FFmpeg libraries used.
[   8.075][v][ffmpeg] Using device 1002:15dd (AMD Radeon(TM) Vega 10 Graphics).
[   8.150][v][vd] Trying hardware decoding via h264-d3d12va-copy.
[   8.151][v][vd] Pixel formats supported by decoder: vulkan cuda dxva2_vld d3d11va_vld d3d11 d3d12 vaapi yuv420p
[   8.151][v][vd] Codec profile: High (0x64)
[   8.151][v][vd] Requesting pixfmt 'd3d12' from decoder.
[   8.151][e][ffmpeg/video] h264: D3D12 decoder doesn't support on this device
[   8.151][e][ffmpeg/video] h264: Failed setup for format d3d12: hwaccel initialisation returned error.

**Comment by dyphire** [comment]
具体的最低要求我也不清楚，大致上需要 N 卡 10 系及以上或 A 卡 RX5000 及以上、win10 22H2 及之后的系统、2022年及之后的显卡驱动、基于 ffmpeg 6.1 以后版本编译的 mpv。Intel 的具体要求不是很确定
