### ISSUE TITLE
窗口尺寸不正常

### ISSUE THREAD

**Issue by nanachisol** [dyphire/mpv-config#48]
自 https://github.com/dyphire/mpv/commit/e1fc4372f3a9b3100fc18348014cfdf47eb5b4a3 版本起，启动时默认窗口尺寸异常。而zhongfly同日编译https://github.com/mpv-player/mpv/commit/293532057ee91a6f52434d6408a836781cfc1573 并无此类现象，至今也并未出现窗口尺寸异常问题

**Comment by dyphire** [comment]
并不是异常，其实是我之前给 mpv 加了几个补丁应用上游 pr，见：https://github.com/dyphire/mpv-winbuild-cmake/commit/b111b64cef2b397c723c09bc1d659b4bcb3a0e22
窗口行为的变化是因为 https://github.com/mpv-player/mpv/pull/13478 这个 pr 更改了 hidpi-window-scale 的默认值。但新行为其实更合理，如果不习惯的话可以在 mpv.conf 中手动启用 hidpi-window-scale 即可

**Comment by dyphire** [comment]
最新提交 https://github.com/dyphire/mpv-config/commit/0ad58e072829ba83bbf2f74090f2b427c9251cbf#diff-9f2dba3e2c4fdeab70a013c047f7a55355689228552c8c8e80be61b857e082b3 中优化了窗口行为，现在的初始窗口大小应该比较合理了
