### ISSUE TITLE
通过菜单加载的蓝光原盘无法显示预览图

### ISSUE THREAD

**Issue by redomCL** [dyphire/mpv-config#51]
你好，打扰了我又遇到问题了，我使用的是你的预览图脚本，使用该菜单下的加载功能加载原盘后，无法显示预览图，不管是加载文件夹形式的原盘还是ISO都不行， https://github.com/tsl0922/mpv-menu-plugin ，打开dvd是可看到一些相关错误日志，打开BD则没有相关错误提示。若将原盘直接拖拽进mpv则没有这个问题
![菜单](https://github.com/dyphire/mpv-config/assets/22269254/a3e2023c-10fc-4cfd-89b3-d75ba90dd931)
![预览](https://github.com/dyphire/mpv-config/assets/22269254/317e13e8-049d-4aa9-aa21-cdfc5df854b9)

**Comment by redomCL** [comment]
![QQ截图20240301002355](https://github.com/dyphire/mpv-config/assets/22269254/fa1966d9-cb33-4179-867f-b53526a1b150)
是我自己的问题，有一段时间没看我设置的conf了

**Comment by redomCL** [comment]
你好大佬，昨晚后面测试发现还是有问题的，以上问题表面上看似解决，但是预览脚本似乎还是有一些问题，其中黑名单实际上并不能关闭对ISO、文件夹形式的DVD和BD的预览，实际上只要是通过拖拽，不管是本地还是windows SMB的网络驱动器，都可以正常预览，只有用上文提到的菜单中（见图1），通过打开文件夹、打开DVD镜像和打开BD镜像来打开相应的文件时才会无法预览。此时文件是以BD://或者DVD://的形式显示（见图2），也就是说这应该是网络挂载形式？所以实际上只有在这里这样设置才关闭了对BD://或者DVD://的预览，黑名单并没有起效
![微信截图_20240301085250](https://github.com/dyphire/mpv-config/assets/22269254/79d1ecaf-3209-4b20-90f9-6e639a2ff5b8)

**Comment by dyphire** [comment]
:// 这类传输协议除了 http 协议外都不被 thumbfast.lua 脚本支持，这是脚本限制。只能向脚本原作者反馈

**Comment by redomCL** [comment]
你试一下直接拖拽文件夹原盘，预览图依然能看到。所以我的看法，1.bdmv其实能看到预览图，2.即便黑名单添加了bdmv，预览图功能还在，这2点是怎么回事？
另外我在黑名单加例如m2ts之类然后单独去播放m2ts文件，此时黑名单是有效的

**Comment by dyphire** [comment]
拖放文件夹自然不会应用黑名单，这是 mpv 的限制，拖放文件夹时加载行为在内部完成。黑名单只能作用于文件加载。当然也可以写脚本 hook 文件夹加载行为，但会影响全局加载，之前有添加过这类脚本，后面被我移除了

**Comment by redomCL** [comment]
了解，问题解决。😀
