### ISSUE TITLE
请教一下有关MPV播放器下端的OSC控制栏的问题

### ISSUE THREAD

**Issue by ads233** [dyphire/mpv-config#52]
MPV的下端控制栏可以降低它的触发边界吗？（或者能不能通过添加快捷键一键锁定下端控制栏不触响应？）我每次想将鼠标指向字幕时它总是连同控制栏一起触发，导致我不能将鼠标指向字幕进行OCR提取词汇分析......

**Comment by dyphire** [comment]
当前使用的 osc 类脚本 uosc 没有提供这类功能，建议自行改用其他更符合使用习惯的 osc 类脚本
