### ISSUE TITLE
如何设置控件的鼠标悬停提示的字体大小呢？

### ISSUE THREAD

**Issue by shanyan-wcx** [dyphire/mpv-config#54]
没找到相关选项

**Comment by shanyan-wcx** [comment]
另外右键菜单如何强制使用深色模式呢，现在是跟随系统的

**Comment by dyphire** [comment]
因为的确没有相关选项，如果真的需要建议向上游脚本作者提交 issue，我个人不感兴趣

> 另外右键菜单如何强制使用深色模式呢，现在是跟随系统的

右键菜单是跟随 mpv 窗口的显示模式切换的，无法单独设置。限制在于 mpv 本身不提供强制深色模式的功能，见： https://github.com/mpv-player/mpv/pull/11473#issuecomment-1489023149
