### ISSUE TITLE
Thank you for sharing. I have a question to ask during the usage process

### ISSUE THREAD

**Issue by laodaoxp** [dyphire/mpv-config#64]
I have set 
gpu-api=vulkan. 
When opening the software root directory, there will be an mpv.20240326-190103-179.log file that cannot be opened.
 I want to know what the file contains
HELP
[mpv.20240326-190445-212.log](https://github.com/dyphire/mpv-config/files/14757446/mpv.20240326-190445-212.log)

**Comment by laodaoxp** [comment]
[mpv.20240326-190202-739.log](https://github.com/dyphire/mpv-config/files/14757442/mpv.20240326-190202-739.log)

**Comment by dyphire** [comment]
This is a damaged file that cannot be opened, and I cannot help you.

**Comment by laodaoxp** [comment]
> 这是一个损坏的文件，无法打开，我无法帮助你。
> 
> 编辑：我尝试过`gpu-api=vulkan`，它对我有用，所以这可能是 vulkan 驱动程序问题。

Solved
Scan with Vulkaninfo

[vulkaninfo.txt](https://github.com/dyphire/mpv-config/files/14782192/vulkaninfo.txt)

已经解决：
VK_LAYER_TENCENT_wegame_cross_overlayIt looks suspicious, I changed the system environment variables and solved the problem

VK_LOADER_LAYERS_DISABLE=VK_LAYER_TENCENT_wegame_cross_overlay
这样就可以了
