### ISSUE TITLE
低概率、随机性的 uosc 界面功能异常

### ISSUE THREAD

**Issue by wathper** [dyphire/mpv-config#65]
当我载入了一些其他脚本的时候。在 mpv 中通过鼠标拖拽切换视频时，会有极高概率触发 bug，导致 uosc 的控件全部失效。或者部分失效。
表现为在播放界面点击 uosc 图标元素后不会执行 uosc 图标元素对应的指令，而是直接触发 mpv 图形界面原本的指令（播放和暂停）。
该 bug 在 mpv 重新启动后将消失，通过鼠标拖拽切换视频后有高概率复现。
额外添加的脚本是： [load_plus.lua](https://github.com/hooke007/MPV_lazy/blob/main/portable_config/scripts/load_plus.lua)、[input_plus.lua](https://github.com/hooke007/MPV_lazy/blob/main/portable_config/scripts/input_plus.lua)

推测这是脚本之间不兼容引发的，但是在将额外添加的脚本移除后，依旧有较低的概率会触发该bug。

bug 的表现形式有所改变，触发 bug 后 uosc 的控件不会全部失效，而是部分功能异常：
有时无法用鼠标滚轮在变速控件上面改变播放速度、有时是 uosc 的进度条无法点击、有时是无法唤出 dyn_menu.lua 菜单。

我对 [mpv config-2024.03.10](https://github.com/dyphire/mpv-config/releases/tag/mpv_config-2024.03.10) 的部分预设做了修改，但是涉及 uosc.conf 的部分修改的相当保守、反复检查后没有发现会导致冲突的地方。也尝试过还原所有与 uosc.conf 相关的更改，但是问题没有解决。

我查看过mpv的日志文件，但是没有与之相关的记录。该 bug 触发的概率较低，找不到什么规律，我也不知道从哪里入手解决。

我想请教作者在配置 mpv 脚本的时候有没有遇到过类似的问题，对此类问题有没有什么好的经验和建议？

**Comment by dyphire** [comment]
这听上去像是 mpv 内部问题，更新你的 mpv 到最新构建后应该会得到修复，最近上游提交 https://github.com/mpv-player/mpv/commit/520849dd48e34e68be09b5f4849fea1d5212fb44 终于修复了这个长久以来的脚本数量限制

**Comment by dyphire** [comment]
mpv 自身的问题请在上游打开 issue 反馈，不要因无关话题重开已关闭的 issue
