### ISSUE TITLE
The audio track has always been defaulted to Japanese language

### ISSUE THREAD

**Issue by laodaoxp** [dyphire/mpv-config#67]
version：[mpv_config-2024.03.10](https://github.com/dyphire/mpv-config/releases/tag/mpv_config-2024.03.10)
Question:The audio track has always been defaulted to Japanese language
set up file mpv.conf

alang=japanese,jpn,jap,ja,jp,english,eng,en
slang=chs,sc,zh-CN,zh-Hans,cht,tc,zh-Hant,zh-HK,zh-TW,chi,zho,zh

Manually modify by oneself
#指定优先使用音轨（使用ISO-639语言代码，优先级按序递减）
alang=zh,chi,chs,sc,zh-hans,en,eng
#指定优先使用字幕轨（使用ISO-639语言代码，优先级按序递减）
slang=zh,chi,chs,sc,zh-hans,en,eng

But when the video is played, it still defaults to Japanese language

But I tested:
Add code to: https://github.com/mpv-player/mpv/releases/tag/v0.37.0 In this version of the file, these two lines of code are functional

![7d5196708d525d195f506fe6b359aa2](https://github.com/dyphire/mpv-config/assets/162548755/c0e6c1c3-7f7f-4ead-8a26-b76222186e42)
![ab7cc1b828a001aa12c999fa9dbf8ad](https://github.com/dyphire/mpv-config/assets/162548755/b5bb7b52-c3a3-4b24-840f-f6ce6934d134)

**Comment by dyphire** [comment]
You also need to modify the following configuration content:
https://github.com/dyphire/mpv-config/blob/13d12fd1addbf6d81419e83927484698ac75cf48/script-opts/trackselect.conf#L21-L25

**Comment by laodaoxp** [comment]
> You also need to modify the following configuration content:
> 
> https://github.com/dyphire/mpv-config/blob/13d12fd1addbf6d81419e83927484698ac75cf48/script-opts/trackselect.conf#L21-L25

thankyou verymuch
