### ISSUE TITLE
在MPV GUI 界面中通过直接粘贴 pikpak 的 URL 来串流播放视频是不可行的。但是使用命令行却可以正常串流。

### ISSUE THREAD

**Issue by wathper** [dyphire/mpv-config#71]
版本：03-10
我在 `mpv.conf`中为 mpv 和 yt-dlp.exe 都设置了本地http代理。
```
http-proxy=http://127.0.0.1:3256
ytdl-raw-options-append=proxy=http://127.0.0.1:3256
```
在MPV GUI 界面中通过直接粘贴 pikpak 串流连接来播放视频会直接黑屏。
使用`mpv 'https://dl-a10b-0862.mypikpak.com/download/?fid=xxxxxxxxx'`则正常播放。

我需要为某个脚本额外配置本地代理吗？还是说是由bug导致的问题？

**Comment by dyphire** [comment]
不具备复现条件，如果确定命令行下可播放，可能是某个脚本影响的，只能建议自己慢慢排查下是哪个的问题

**Comment by dyphire** [comment]
看上去又是 ytdl 的问题

**Comment by dyphire** [comment]
我又看了眼这个问题，实际上应该是你的代理设置有问题，正确的设置应为：
```ini
ytdl-raw-options-append=proxy=http://127.0.0.1:3256
stream-lavf-o-append=http_proxy=http://127.0.0.1:3256
```
命令行之所以可以播放应该是终端直接走了代理软件

我其实不推荐这种写死代理的方式，由代理软件（clash 等）使用 tun 模式接管网络流量是更合适的方式，也是我的用法；亦或者你可以选择使用脚本自动设置代理：[set_proxy.lua](https://gist.github.com/zhongfly/2a4e47b844edc22d0cc816f751fe9128)
