### ISSUE TITLE
updater.ps1中关于ffmpeg的链接有问题

### ISSUE THREAD

**Issue by in-out** [dyphire/mpv-config#75]
$api_gh = "https://api.github.com/repos/dyphire/mpv-winbuild-cmake/releases/latest"
这个链接并不存在

**Comment by dyphire** [comment]
没想到有人会用这个的 ffmpeg，当时替换的时候没注意
先手动把链接改成 https://api.github.com/repos/dyphire/mpv-winbuild/releases/latest

**Comment by dyphire** [comment]
已在 https://github.com/dyphire/mpv-packaging/commit/12cfefaaa6049adf643a25bdd90b2856ecf1ef7c 中修复，更新到今天的发布会自动替换旧 updater.ps1 文件
