### ISSUE TITLE
make a 4k version uosc.lua?

### ISSUE THREAD

**Issue by offferu** [dyphire/mpv-config#8]
the uosc.lua is looking nice! However, in 4k screen the float control buttons too small. Could you make a version for high resolution monitor? 
Thanks!

**Comment by dyphire** [comment]
This is caused by the `hidpi-window-scale=no` parameter in the mpv.conf file. You can improve it if you comment it out.
This is a legacy item in config refactoring. I will fix it next. 
Thanks for the report

**Comment by dyphire** [comment]
> This is caused by the `hidpi-window-scale=no` parameter in the mpv.conf file. You can improve it if you comment it out. 

After testing, this is inaccurate. The icon size after `hidpi-window-scale` is enabled is affected by the DPI of the display.

I'm not sure whether this is the effect you want. 
I suggest you feed back this problem to the developer of the uosc.lua script and open an issue there: https://github.com/tomasklaen/uosc/issues

**Comment by dyphire** [comment]
Ah, I made a stupid mistake here. The usoc.lua script provides the option to adjust the UI scaling.
Please refer to https://github.com/dyphire/mpv-config/blob/929abb1ae49e75fcefcbdd1d388e5e75abe7f821/script-opts/uosc.conf#L127-L130

```
# Scale the interface by this factor
ui_scale=1
# Adjust the text scaling to fit your font
font_scale=1
```
I think that's exactly what you want.

**Comment by dyphire** [comment]
> This is a legacy item in config refactoring. I will fix it next. 

Done.
I believe the latest commit will make it work better. Can you test it?

**Comment by offferu** [comment]
yes, work like a charm now

**Comment by offferu** [comment]
不过还是将hidpi-window-scale=no启用了，启用了功能键一样变大了，估计是ui_scale=1.6 （3840x2400)的显示器 起作用了

**Comment by dyphire** [comment]
> 不过还是将hidpi-window-scale=no启用了，启用了功能键一样变大了，估计是ui_scale=1.6 （3840x2400)的显示器 起作用了

`ui_scale`选项是手动指定uosc.lua脚本UI的缩放比例，启用`hidpi-window-scale`则是自动获取显示器的DPI进行缩放。
能达到一样的效果，但后者适用性更强，因为它可以自动适用不同DPI缩放的显示器，而`ui_scale`每次切换不同DPI显示器时都要重新指定缩放比例。

考虑到兼容度我最终还是采用了hidpi方案，不过`ui_scale`方案一样有它的优势，就是显示器指定不太合理的DPI缩放时它可以避免UI缩放过大（有些人喜欢提高DPI）

**Comment by offferu** [comment]
> > 不过还是将hidpi-window-scale=no启用了，启用了功能键一样变大了，估计是ui_scale=1.6 （3840x2400)的显示器 起作用了
> 
> `ui_scale`选项是手动指定uosc.lua脚本UI的缩放比例，启用`hidpi-window-scale`则是自动获取显示器的DPI进行缩放。 能达到一样的效果，但后者适用性更强，因为它可以自动适用不同DPI缩放的显示器，而`ui_scale`每次切换不同DPI显示器时都要重新指定缩放比例以获得合适的显示效果。
> 
> 考虑到兼容度我最终还是采用了hidpi方案，不过`ui_scale`方案一样有它的优势，就是显示器指定不太合理的DPI缩放时它可以避免UI缩放失调（有些人喜欢提高/降低DPI）

启用hidpi-window-scale后发现一个缺点就是：本来是1080p的视频，不应该铺满屏幕，但它还是铺满了（将1920x1080拉伸为3840x2160），而我喜欢看原尺寸大小，对于小于4k的视频，不希望播放器拉伸

**Comment by offferu** [comment]
> > > 不过还是将hidpi-window-scale=no启用了，启用了功能键一样变大了，估计是ui_scale=1.6 （3840x2400)的显示器 起作用了
> > 
> > 
> > `ui_scale`选项是手动指定uosc.lua脚本UI的缩放比例，启用`hidpi-window-scale`则是自动获取显示器的DPI进行缩放。 能达到一样的效果，但后者适用性更强，因为它可以自动适用不同DPI缩放的显示器，而`ui_scale`每次切换不同DPI显示器时都要重新指定缩放比例以获得合适的显示效果。
> > 考虑到兼容度我最终还是采用了hidpi方案，不过`ui_scale`方案一样有它的优势，就是显示器指定不太合理的DPI缩放时它可以避免UI缩放失调（有些人喜欢提高/降低DPI）
> 
> 启用hidpi-window-scale后发现一个缺点就是：本来是1080p的视频，不应该铺满屏幕，但它还是铺满了（将1920x1080拉伸为3840x2160），而我喜欢看原尺寸大小，对于小于4k的视频，不希望播放器拉伸

＜img src="https://img77.pixhost.to/images/69/306328413_scaled-resolutionnative-resolution.png"＞

**Comment by dyphire** [comment]
> 启用hidpi-window-scale后发现一个缺点就是：本来是1080p的视频，不应该铺满屏幕，但它还是铺满了（将1920x1080拉伸为3840x2160），而我喜欢看原尺寸大小，对于小于4k的视频，不希望播放器拉伸

hidpi-window-scale确实会影响到window-scale参数，导致窗口缩放受dpi影响。我个人不怎么纠结这个，有好的放大缩小算法（着色器）就没什么影响，不过这都是视喜好而定的，按自己习惯的调整就好

> https://img77.pixhost.to/images/69/306328413_scaled-resolutionnative-resolution.png 
为什么要使用gamma2.4的滤镜？

**Comment by offferu** [comment]
> > 启用hidpi-window-scale后发现一个缺点就是：本来是1080p的视频，不应该铺满屏幕，但它还是铺满了（将1920x1080拉伸为3840x2160），而我喜欢看原尺寸大小，对于小于4k的视频，不希望播放器拉伸
> 
> hidpi-window-scale确实会影响到window-scale参数，导致窗口缩放受dpi影响。我个人不怎么纠结这个，有好的放大缩小算法（着色器）就没什么影响。不过这都是视喜好而定的，按自己习惯的调整就好
> 
> > https://img77.pixhost.to/images/69/306328413_scaled-resolutionnative-resolution.png
> 
> 为什么要使用gamma2.4的滤镜？
这个不懂怎么调的，我显卡Nvidia RTX 3050 Ti Laptop.

**Comment by dyphire** [comment]
> 这个不懂怎么调的，我显卡Nvidia RTX 3050 Ti Laptop.

![](https://cdn.jsdelivr.net/gh/dyphire/PicGo/img/2022/09/17/20220917212622.png)
跟显卡没关系，跟显示器有关。好奇你为什么使用gamma2.4的滤镜

**Comment by offferu** [comment]
> 

https://img77.pixhost.to/images/118/308067661_skin.png

我改好了，顺便说一句，更新后的skin更漂亮了，多谢作者的付出

**Comment by dyphire** [comment]
> > 
> 
> https://img77.pixhost.to/images/118/308067661_skin.png
> 
> 我改好了，顺便说一句，更新后的skin更漂亮了，多谢作者的付出

喜欢就好，左边那个状态的图标还是不太协调，又改了下，新的图标应该更舒适一点。
