### ISSUE TITLE
请问 mpv_config-2024.04.06 在播放 WebDAV 中的视频时，会导致win的右键菜单和文件管理器出现异常吗？

### ISSUE THREAD

**Issue by wathper** [dyphire/mpv-config#85]
出现的问题：
播放 WebDAV网络驱动器 中的视频并切换剧集后，有概率使win系统出现交互功能异常，表现为：在桌面上单击右键后，右键菜单中的选项丢失。同时在文件管理器中无法唤起右键菜单。（此时mpv播放器的功能是正常的，日志中也没有相关的报错）。
关闭mpv播放器后，win系统功能全部恢复正常。

起初我认为是系统的问题。
但是最近我为了使用svp补帧，将`notify_media.lua`以及`MPVMediaControl.exe`移除后，发现播放 WebDAV 内容时不会再触发“win系统出现交互功能异常”的问题了。

有可能是“基于 IPC 管道实现的 SMTC 功能”存在什么兼容性的问题吗？

**Comment by dyphire** [comment]
还有这问题？能发个录屏看下嘛
notify_media.lua 脚本对我来说最大的作用就是实现蓝牙耳机的播放控制功能，但我对它的实现方式一直不满意，这个功能更应该在 mpv 上游实现。脚本存在占用 IPC 管道、 MPVMediaControl.exe 常驻后台和概率失效等问题，所以一度被移除
如果可以确认是这个脚本的问题，我会再次移除它，考虑在 mpv 那边打开一个功能请求

**Comment by dyphire** [comment]
再次移除该脚本，在上游打开了相应的功能请求
顺便发现启用 input.conf 的功能按键后也可以实现对部分蓝牙耳机的媒体控制功能的支持，不知道为什么之前测试的时候不起作用
这样一来这个脚本的意义也就没有了，无论这个 bug 是不是它引起的都没必要保留了

**Comment by dyphire** [comment]
> 顺便发现启用 input.conf 的功能按键后也可以实现对部分蓝牙耳机的媒体控制功能的支持，不知道为什么之前测试的时候不起作用

好了，经过反复测试我定位到为什么蓝牙耳机的媒体控制功能时灵时不灵了。是 inputevent.lua 劫持了对应的功能键响应，在提交 https://github.com/dyphire/mpv-config/commit/616f9fcc7272bd14856660513f1f732906da63ca 中修复
