### ISSUE TITLE
关于优化配置

### ISSUE THREAD

**Issue by sqq135** [dyphire/mpv-config#89]
从Lazy的讨论那里过来，大佬给出自己库中的脚本链接，并指出在lua文件后面的备注中表明有优化。

这就让我比较纠结，一方面想用大佬改进过的脚本，又担心如果想在脚本的github中提建议，会不小心找错反馈方。能否在改进后的脚本中记录一下改进的内容，让我这样的伸手党更好选择[捂脸]

**Comment by dyphire** [comment]
一些脚本的修改基本是重构了，不可能注明修改内容。修改内容也不适合在脚本中注释，只会造成无限膨胀。真那么在意修改了什么，自行查看对应脚本的 commit 历史
