### ISSUE TITLE
两套皮肤同时存在

### ISSUE THREAD

**Issue by offferu** [dyphire/mpv-config#9]
https://i.ibb.co/j6j237M/two-skins.png

如图，请问怎样取消彩色那个，仅保留uosc

**Comment by dyphire** [comment]
为什么要同时使用两套osc脚本？把另一个osc的脚本删掉就是了

**Comment by offferu** [comment]
请问删掉哪个文件夹下的什么文件就好了？

**Comment by dyphire** [comment]
> 请问删掉哪个文件夹下的什么文件就好了？

scripts文件夹下删除名称包含osc的脚本（非uosc.lua），别忘了在script-opts文件夹下还要删除同名配置文件。

如果参考我的mpv配置应该不会此问题，估计当做是替换mpvnet配置出的问题吧。两者之所以使用不同osc脚本只是为了差异化（其实我基本不用mpvnet了

**Comment by offferu** [comment]
> > 请问删掉哪个文件夹下的什么文件就好了？
> 
> scripts文件夹下删除名称包含osc的脚本（非uosc.lua），别忘了在script-opts文件夹下还要删除同名配置文件。
> 
> 如果参考我的mpv配置应该不会出现此问题，就当做是自行替换mpvnet配置出的问题吧。两者之所以使用不同osc脚本只是为了差异化（其实是我基本不用mpvnet了

搞定，多谢！
