### ISSUE TITLE
请问左上角的1 -- continue? 13  [EN/IG]是什么意思啊，是哪个脚本和插件在生效呢？

### ISSUE THREAD

**Issue by hunter8605** [dyphire/mpv-config#90]
![True Lies 1994 2160p MA WEB-DL DDP5 1 Atmos DV HDR H 265-BHYS@OurBits mkv-00_00_03 086-0001](https://github.com/dyphire/mpv-config/assets/45852526/a3a55580-1752-4167-bf4f-dde182cc0f34)
感觉是一个比较低级的问题，但是谷歌百度查了好多都查不到，只能来这里问了，麻烦大佬了。

**Comment by hunter8605** [comment]
再其他Issues找到了答案[https://github.com/dyphire/mpv-config/issues/17#issuecomment-1403530109](url)

**Comment by dyphire** [comment]
原有的显示确实很不易懂，在新提交中优化了显示消息和快捷键
