### ISSUE TITLE
打开视频后 mpv 黑屏闪退

### ISSUE THREAD

**Issue by wordpure** [dyphire/mpv-config#92]
版本：mpv_config-2024.05.12
配置：默认配置

<details>
<summary>硬件信息</summary>

- CPU：Intel(R) Core(TM) i5-7200U CPU @ 2.50GHz   2.70 GHz
- GPU：Intel(R) HD Graphics 620、NVIDIA GeForce 940MX

</details>

<details>
<summary>错误日志</summary>

```log
[   3.008][e][vo/gpu-next/libplacebo] Failed creating FBO texture! Disabling advanced rendering..
[   3.008][e][vo/gpu-next/libplacebo] Failed dispatching hook: `get_tex` callback failed?
[   3.008][e][vo/gpu-next/libplacebo] Failed executing hook, disabling
[   3.008][e][vo/gpu-next/libplacebo] Failed creating FBO texture! Disabling advanced rendering..
```

[完整日志](https://github.com/dyphire/mpv-config/files/15485456/mpv.log)

[测试视频](https://wormhole.app/0Bd8Y#o1jK0bVUyDvnscz_PyKrxA)

</details>

**Comment by dyphire** [comment]
> 硬件信息
> * CPU：Intel(R) Core(TM) i5-7200U CPU @ 2.50GHz   2.70 GHz
> * GPU：Intel(R) HD Graphics 620、NVIDIA GeForce 940MX

这个硬件配置就不要使用这个仓库的 mpv.conf 配置文件了，性能太低了。mpv 默认配置都带不动的，得 --profile=fast 下才能用

> 错误日志
> ```
> [   3.008][e][vo/gpu-next/libplacebo] Failed creating FBO texture! Disabling advanced rendering..
> [   3.008][e][vo/gpu-next/libplacebo] Failed dispatching hook: `get_tex` callback failed?
> [   3.008][e][vo/gpu-next/libplacebo] Failed executing hook, disabling
> [   3.008][e][vo/gpu-next/libplacebo] Failed creating FBO texture! Disabling advanced rendering..
> ```

这个报错就是显卡驱动不支持对应的硬解格式又没回退软解，还是跟设备太旧有关。改用 mpv 默认的 --hwdec=no 软解方案

**Comment by wordpure** [comment]
感谢大佬指点，确实是 profile 和 hwdec 的问题。

测试后发现，把 `hwdec=d3d12va-copy,auto-copy` 改成 `d3d11va` 或 `no`， `profile=Tscale` 引入的 `video-sync=display-resample` 改成 `audio` 或 `desync` 就可以正常播放。
