### ISSUE TITLE
how to remember window-maximized without changing video graphics for Movie?

### ISSUE THREAD

**Issue by candrapersada** [dyphire/mpv-config#93]
how to use window-maximized without changing video graphics for Movie 360p or 480p?

https://github.com/dyphire/mpv-config/assets/36833664/a900fa45-2f28-47cb-9858-6cac24092ef5

https://github.com/dyphire/mpv-config/assets/36833664/fc37e832-5946-48ef-9fca-609ac7e8a917

**Comment by dyphire** [comment]
Can't understand what you are trying to express, you probably need to describe it more clearly.

**Comment by candrapersada** [comment]
Why does video movement often break when using window-maximized?
![image](https://github.com/dyphire/mpv-config/assets/36833664/9e200dc8-5a00-40f2-8972-f5ada34101f7)

**Comment by dyphire** [comment]
> Why does video movement often break when using window-maximized?

Obviously that's because your equipment is underperforming. It is mentioned in the release notes that the minimum requirement for graphics cards configured with this repository is GTX 1060, and you will need to adjust the parameters in mpv.conf to suit your machine.

**Comment by candrapersada** [comment]
but the problem doesn't occur if you don't use window-maximized
![image](https://github.com/dyphire/mpv-config/assets/36833664/96780ddc-fa29-47ad-94b0-69c63e01d9e8)

**Comment by dyphire** [comment]
> but the problem doesn't occur if you don't use window-maximized

What's so incomprehensible about this? The video will be scale as the window is scale, and mpv will use the advanced shader and scaling algorithm in the mpv.conf configuration to upscaling. Your device is not capable enough to run them, resulting in frame drops.

You need to understand how the player works first.
