### ISSUE TITLE
预设下混滤镜dynaudnorm导致背景音量忽高忽低

### ISSUE THREAD

**Issue by nanachisol** [dyphire/mpv-config#99]
**mpv Information**
```
mpv v0.38.0-539-g1225bcbd Copyright © 2000-2024 mpv/MPlayer/mplayer2 projects
 built on Jun 24 2024 02:05:24
libplacebo version: v7.349.0 (v7.349.0-rc1-3-g1fd3c7b-dirty)
FFmpeg version: N-115976-g0b67c83b2
FFmpeg library versions:
   libavcodec      61.8.100
   libavdevice     61.2.100
   libavfilter     10.2.102
   libavformat     61.3.104
   libavutil       59.25.100
   libswresample   5.2.100
   libswscale      8.2.100
```
**Other Information**
- Windows version:Windows 11 Version 10.0.22631.3737
- GPU model, driver and version:ryzen 2700u with Vega10,AMD 24.5.1
- Source of mpv:zhongfly
- Introduced in version:N/A

**Reproduction Steps**
切换音频预设方案至loudnorm背景音量正常
或者使用其它方案，设置代码如下：[loudnorm+重采样](https://bbs.acgrip.com/forum.php?mod=viewthread&tid=10324&page=20#pid107021)背景音量也正常，但loudnorm会导致掉帧，看相关讨论需要2pass。另外af-append与af-pre有什么区别？官方文档没太看懂
```
af-append = loudnorm:I=-14:LRA=11:TP=-1
af-append = aresample=osr=48000:osf=s16:resampler=soxr:precision=28
```

**Expected Behavior**
播放影片过程中，使用预设dynaudnorm，人物对话和背景音量正常

**Actual Behavior**
人物对话开始至结束时，导致背景音量忽高忽低

**Log File**
无

**Sample Files**
https://oshi.at/ggdL

**相关讨论**
https://www.reddit.com/r/mpv/comments/1au7ty2/dynaudnorm_or_loudnorm_audio_filters_for_everyday/
https://www.reddit.com/r/mpv/comments/146ntxa/is_there_any_trick_to_boost_low_ac3_audio_volume/
https://www.reddit.com/r/mpv/comments/1d4he0k/auto_volume_leveller/
https://ffmpeg.org/ffmpeg-filters.html#dynaudnorm
https://github.com/mpv-player/mpv/issues/10767
https://github.com/mpv-player/mpv/issues/6563

**Comment by dyphire** [comment]
> 按照官方手册里的说明。。R 值越大，声音响度越统一吧？我看你更新之后改成了 r=0.1，难道 r 值调小一点比较好？ 我自己简单的用的lavfi=[dynaudnorm=p=0.65:r=0.9] 搞不懂的就用的默认值。。。

改的滤镜参数也是很久之前在其他地方抄的作业，在测试的时候就不是很满意
> dynaudnorm 滤镜改动参数后虽然也不再产生这个问题，但有时人声会随背景音变大，感觉依然不理想

之后又测试调整了下，推送了个新的提交，让我们看看这次的表现和反馈如何

**Comment by dyphire** [comment]
> > > 按照官方手册里的说明。。R 值越大，声音响度越统一吧？我看你更新之后改成了 r=0.1，难道 r 值调小一点比较好？ 我自己简单的用的lavfi=[dynaudnorm=p=0.65:r=0.9] 搞不懂的就用的默认值。。。
> > 
> > 
> > 改的滤镜参数也是很久之前在其他地方抄的作业，在测试的时候就不是很满意
> > > dynaudnorm 滤镜改动参数后虽然也不再产生这个问题，但有时人声会随背景音变大，感觉依然不理想
> > 
> > 
> > 之后又测试调整了下，推送了个新的提交，让我们看看这次的表现和反馈如何
> 
> 感谢开发者工作，现在多声道下混没有遇到背景音量忽高忽低的问题了。 但是 audio-filter 配置预设，由可能导致音频切换延迟，但不确定是否为电脑性能，或者蓝牙耳机，或驱动程序或其他原因。 操作步骤如下： 1.正常播放视频，外放 stereo 2.使用蓝牙耳机设备 3.声音未同步切换，大约需等待 4-5 秒，蓝牙耳机恢复正常。快进或后退，可快速恢复声音播放。 4.由蓝牙耳机切换至stereo ，现象和第三步一致。 5.使用 mpv --no-config 播放视频；或首先使用蓝牙耳机，再播放视频。均无以上现象发生。
> 
> [mpv.log](https://github.com/user-attachments/files/16175672/mpv.log)

我可以通过你提供的步骤使用蓝牙耳机复现它，这可能是系统或 mpv 上的某种问题导致的
目前只能取消自动应用音频滤镜来避免它，改用快捷键切换：https://github.com/dyphire/mpv-config/commit/0fa283e

**Comment by dyphire** [comment]
其实我可以写个脚本在音频设备切换时自动执行帧步进帧步退的操作来快速“修复”它，但这种解决方案不是很优雅且不使用自动滤镜时也不需要这种处理
